2024-03-13 16:15:39,897 INFO    StreamThr :19860 [internal.py:wandb_internal():86] W&B internal server running at pid: 19860, started at: 2024-03-13 16:15:39.896722
2024-03-13 16:15:39,898 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status
2024-03-13 16:15:39,903 INFO    WriterThread:19860 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\run-yw706lp8.wandb
2024-03-13 16:15:39,905 DEBUG   SenderThread:19860 [sender.py:send():380] send: header
2024-03-13 16:15:39,905 DEBUG   SenderThread:19860 [sender.py:send():380] send: run
2024-03-13 16:15:41,443 INFO    SenderThread:19860 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files
2024-03-13 16:15:41,443 INFO    SenderThread:19860 [sender.py:_start_run_threads():1122] run started: yw706lp8 with start time 1710317739.897722
2024-03-13 16:15:41,461 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 16:15:41,462 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: check_version
2024-03-13 16:15:44,679 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 16:15:44,721 DEBUG   HandlerThread:19860 [system_info.py:__init__():32] System info init
2024-03-13 16:15:44,721 DEBUG   HandlerThread:19860 [system_info.py:__init__():47] System info init done
2024-03-13 16:15:44,721 INFO    HandlerThread:19860 [system_monitor.py:start():181] Starting system monitor
2024-03-13 16:15:44,721 INFO    SystemMonitor:19860 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 16:15:44,721 INFO    HandlerThread:19860 [system_monitor.py:probe():201] Collecting system info
2024-03-13 16:15:44,726 INFO    SystemMonitor:19860 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 16:15:44,726 INFO    SystemMonitor:19860 [interfaces.py:start():190] Started disk monitoring
2024-03-13 16:15:44,727 INFO    SystemMonitor:19860 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 16:15:44,728 INFO    SystemMonitor:19860 [interfaces.py:start():190] Started memory monitoring
2024-03-13 16:15:44,755 INFO    SystemMonitor:19860 [interfaces.py:start():190] Started network monitoring
2024-03-13 16:15:44,765 DEBUG   HandlerThread:19860 [system_info.py:probe():196] Probing system
2024-03-13 16:15:44,765 DEBUG   HandlerThread:19860 [system_info.py:probe():244] Probing system done
2024-03-13 16:15:44,765 DEBUG   HandlerThread:19860 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T08:15:44.765647', 'startedAt': '2024-03-13T08:15:39.882719', 'docker': None, 'cuda': None, 'args': ('--task=W', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 176.55047225952148}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 16:15:44,765 INFO    HandlerThread:19860 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 16:15:44,765 INFO    HandlerThread:19860 [system_monitor.py:probe():214] Publishing system info
2024-03-13 16:15:44,765 DEBUG   HandlerThread:19860 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 16:15:44,766 DEBUG   HandlerThread:19860 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 16:15:44,766 DEBUG   HandlerThread:19860 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 16:15:44,784 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:45,480 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\conda-environment.yaml
2024-03-13 16:15:45,480 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\requirements.txt
2024-03-13 16:15:46,811 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:48,855 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:50,890 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:51,542 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\conda-environment.yaml
2024-03-13 16:15:51,707 DEBUG   HandlerThread:19860 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 16:15:51,707 INFO    HandlerThread:19860 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 16:15:51,727 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:15:51,727 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:15:51,727 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:15:51,728 DEBUG   SenderThread:19860 [sender.py:send():380] send: files
2024-03-13 16:15:51,728 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 16:15:51,739 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:15:51,739 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:15:51,741 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:15:52,556 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\conda-environment.yaml
2024-03-13 16:15:52,557 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-metadata.json
2024-03-13 16:15:52,931 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:54,965 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:56,778 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:15:57,002 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:57,119 DEBUG   SenderThread:19860 [sender.py:send():380] send: telemetry
2024-03-13 16:15:57,119 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:15:57,307 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:15:57,308 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:15:57,308 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:15:57,309 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:15:57,576 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:15:57,577 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:15:59,042 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:15:59,158 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:15:59,158 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:15:59,159 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:15:59,160 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:15:59,160 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:15:59,161 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:15:59,161 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:15:59,162 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:15:59,595 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:15:59,596 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:01,080 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:01,607 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:01,744 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:01,744 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:01,745 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:01,745 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:02,608 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:02,749 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:03,120 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:03,583 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:03,584 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:03,584 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:03,585 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:03,586 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:03,586 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:03,586 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:03,587 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:03,611 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:03,612 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:05,151 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:05,622 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:06,189 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:06,189 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:06,190 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:06,190 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:06,627 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:06,754 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:16:06,754 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:16:06,754 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:16:06,755 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:16:07,200 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:07,634 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:07,944 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD32A3400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:16:07,944 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:16:07,944 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:16:08,079 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:08,086 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:08,087 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:08,088 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:08,088 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:08,089 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:08,089 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:08,089 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:08,090 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:08,639 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:09,258 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:09,647 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:10,709 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:10,710 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:10,710 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:10,711 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:11,287 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:11,654 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:11,655 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:12,522 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:12,523 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:12,524 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:12,524 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:12,525 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:12,525 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:12,526 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:12,526 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:12,669 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:13,325 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:13,542 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:13,684 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:14,700 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\config.yaml
2024-03-13 16:16:15,125 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:15,126 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:15,126 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:15,127 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:15,404 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:15,715 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:16,941 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:16,941 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:16,942 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:16,942 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:16,943 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:16,944 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:16,944 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:16,945 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:17,436 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:17,733 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:17,734 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:18,956 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:18,976 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD34958A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:16:18,976 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:16:18,976 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:16:19,467 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:19,550 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:19,551 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:19,551 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:19,552 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:19,739 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:21,470 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:21,471 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:21,471 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:21,472 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:21,473 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:21,473 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:21,473 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:21,474 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:21,493 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:21,745 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:21,746 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:21,760 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:16:21,776 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:16:21,777 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:16:23,525 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:23,761 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:24,076 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:24,077 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:24,077 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:24,077 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:24,078 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:24,776 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:25,554 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:25,789 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:25,952 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:25,953 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:25,954 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:25,954 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:25,955 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:25,955 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:25,955 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:25,956 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:26,791 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:27,594 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:27,806 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:28,545 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:28,546 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:28,546 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:28,547 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:28,811 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:29,588 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:29,627 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:29,815 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:30,432 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:30,433 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:30,434 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:30,434 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:30,435 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:30,436 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:30,436 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:30,436 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:30,819 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:31,221 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3494FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:16:31,221 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:16:31,221 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:16:31,222 INFO    wandb-upload_0:19860 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000027BD3494FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3494FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3494FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 16:16:31,659 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:31,835 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:33,034 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:33,035 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:33,035 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:33,036 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:33,690 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:33,847 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:33,847 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:34,938 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:34,938 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:34,939 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:34,940 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:34,941 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:34,941 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:34,942 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:34,942 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:34,943 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:35,730 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:35,855 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:35,856 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:36,775 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:16:36,775 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:16:36,775 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:16:37,542 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:37,543 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:37,543 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:37,544 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:37,772 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:37,884 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:39,389 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:39,390 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:39,391 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:39,391 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:39,392 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:39,393 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:39,393 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:39,394 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:39,811 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:39,892 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:39,893 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:40,400 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:41,851 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:41,897 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:41,996 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:41,997 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:41,997 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:41,998 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:42,899 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:43,816 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:43,817 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:43,818 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:43,818 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:43,819 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:43,820 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:43,820 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:43,821 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:43,885 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:43,913 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:43,914 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:44,768 DEBUG   SystemMonitor:19860 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 16:16:44,769 DEBUG   SenderThread:19860 [sender.py:send():380] send: stats
2024-03-13 16:16:45,782 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:45,901 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD32A3400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:16:45,901 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:16:45,901 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:16:45,943 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:45,966 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:46,434 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:46,435 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:46,435 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:46,436 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:46,947 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:47,953 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:47,986 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:48,331 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:48,331 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:48,332 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:48,333 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:48,333 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:48,334 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:48,334 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:48,335 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:48,959 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:49,971 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:50,009 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:50,944 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:50,945 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:50,945 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:50,945 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:50,946 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:50,980 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:51,792 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:16:51,792 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:16:51,792 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:16:51,792 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:16:52,014 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:52,031 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:52,756 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:52,756 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:52,757 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:52,757 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:52,758 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:52,759 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:52,759 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:52,760 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:53,022 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:54,055 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:54,071 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:55,356 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:55,357 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:55,357 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:55,358 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:56,086 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:56,087 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:56,103 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:56,373 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:16:57,254 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:57,255 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:57,256 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:57,256 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:57,257 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:57,258 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:57,258 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:57,258 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:16:58,122 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:16:58,123 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:16:58,143 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:16:59,843 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:16:59,844 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:16:59,844 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:16:59,845 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:00,151 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:00,171 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:01,677 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:01,678 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:01,679 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:01,679 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:01,680 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:01,680 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:01,681 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:01,681 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:01,682 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:02,193 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:02,193 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:02,209 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:04,243 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:04,282 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:04,283 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:04,283 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:04,283 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:05,234 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:05,588 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3495A50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:05,588 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:17:05,588 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:06,151 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:06,152 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:06,153 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:06,153 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:06,154 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:06,154 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:06,155 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:06,155 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:06,268 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:06,268 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:06,284 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:06,792 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:17:06,808 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:17:06,809 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:17:06,809 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:17:07,170 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:08,304 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:08,321 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:08,753 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:08,753 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:08,754 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:08,754 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:09,316 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:10,348 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:10,365 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:10,628 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:10,629 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:10,630 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:10,630 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:10,631 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:10,631 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:10,632 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:10,632 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:11,352 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:12,382 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:12,401 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:12,641 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:13,231 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:13,232 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:13,232 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:13,233 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:13,392 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:14,423 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:14,441 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:14,779 DEBUG   SenderThread:19860 [sender.py:send():380] send: stats
2024-03-13 16:17:15,116 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:15,117 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:15,118 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:15,119 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:15,119 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:15,120 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:15,120 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:15,121 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:15,433 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:16,474 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:16,536 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:17,702 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:17,702 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:17,703 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:17,703 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:17,704 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:18,506 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:18,557 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:19,551 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:19,552 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:19,553 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:19,553 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:19,554 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:19,554 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:19,554 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:19,555 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:20,553 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:20,553 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:20,585 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:21,794 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:17:21,811 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:17:21,826 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:17:21,827 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:17:22,149 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:22,149 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:22,150 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:22,150 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:22,590 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:22,607 ERROR   gpu       :19860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:17:23,164 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:24,036 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:24,036 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:17:24,037 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:24,038 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:24,038 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:24,039 DEBUG   SenderThread:19860 [sender.py:send():380] send: history
2024-03-13 16:17:24,039 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:17:24,039 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:24,183 DEBUG   SenderThread:19860 [sender.py:send():380] send: exit
2024-03-13 16:17:24,183 INFO    SenderThread:19860 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 16:17:24,183 INFO    SenderThread:19860 [sender.py:send_exit():587] handling runtime: 99
2024-03-13 16:17:24,184 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:24,184 INFO    SenderThread:19860 [sender.py:send_exit():593] send defer
2024-03-13 16:17:24,184 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,184 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 16:17:24,184 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,185 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 16:17:24,185 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 1
2024-03-13 16:17:24,185 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,185 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 16:17:24,185 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,185 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 16:17:24,185 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 2
2024-03-13 16:17:24,185 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,185 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 16:17:24,185 INFO    HandlerThread:19860 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 16:17:24,185 DEBUG   SystemMonitor:19860 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 16:17:24,192 DEBUG   SystemMonitor:19860 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 16:17:24,192 INFO    HandlerThread:19860 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 16:17:24,193 INFO    HandlerThread:19860 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 16:17:24,231 INFO    HandlerThread:19860 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 16:17:24,231 INFO    HandlerThread:19860 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 16:17:24,231 INFO    HandlerThread:19860 [interfaces.py:finish():202] Joined network monitor
2024-03-13 16:17:24,232 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,232 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 16:17:24,233 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 3
2024-03-13 16:17:24,233 DEBUG   SenderThread:19860 [sender.py:send():380] send: stats
2024-03-13 16:17:24,233 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,233 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 16:17:24,233 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,233 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 16:17:24,233 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 4
2024-03-13 16:17:24,234 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,234 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 16:17:24,234 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,234 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 16:17:24,234 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 5
2024-03-13 16:17:24,234 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,234 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 16:17:24,235 DEBUG   SenderThread:19860 [sender.py:send():380] send: summary
2024-03-13 16:17:24,235 INFO    SenderThread:19860 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:17:24,236 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,236 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 16:17:24,236 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 6
2024-03-13 16:17:24,236 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,236 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 16:17:24,236 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,236 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 16:17:24,237 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 7
2024-03-13 16:17:24,237 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:24,237 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:24,237 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 16:17:24,237 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:24,237 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 16:17:24,612 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json
2024-03-13 16:17:24,613 INFO    Thread-12 :19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:25,194 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:25,929 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 8
2024-03-13 16:17:25,930 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:25,930 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:25,930 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 16:17:25,930 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:25,930 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 16:17:25,930 INFO    SenderThread:19860 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 16:17:25,931 INFO    SenderThread:19860 [job_builder.py:_get_source_type():404] no source found
2024-03-13 16:17:25,931 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 9
2024-03-13 16:17:25,931 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:25,931 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 16:17:25,932 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:25,932 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 16:17:25,932 INFO    SenderThread:19860 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 16:17:26,198 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:26,622 INFO    SenderThread:19860 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log
2024-03-13 16:17:26,623 INFO    SenderThread:19860 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files
2024-03-13 16:17:26,623 INFO    SenderThread:19860 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\conda-environment.yaml conda-environment.yaml
2024-03-13 16:17:26,624 INFO    SenderThread:19860 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\config.yaml config.yaml
2024-03-13 16:17:26,626 INFO    SenderThread:19860 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\output.log output.log
2024-03-13 16:17:26,628 INFO    SenderThread:19860 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\requirements.txt requirements.txt
2024-03-13 16:17:26,631 INFO    SenderThread:19860 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-metadata.json wandb-metadata.json
2024-03-13 16:17:26,631 INFO    SenderThread:19860 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161539-yw706lp8\files\wandb-summary.json wandb-summary.json
2024-03-13 16:17:26,633 INFO    SenderThread:19860 [sender.py:transition_state():613] send defer: 10
2024-03-13 16:17:26,633 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:26,633 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:17:26,634 INFO    HandlerThread:19860 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 16:17:26,636 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: defer
2024-03-13 16:17:26,636 INFO    SenderThread:19860 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 16:17:26,636 INFO    SenderThread:19860 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 16:17:27,213 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:27,214 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:28,214 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:28,215 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:29,217 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:29,218 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:30,218 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:30,219 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:31,219 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:31,219 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:32,232 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:32,233 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:33,248 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:33,248 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:33,249 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:34,258 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:34,259 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:34,838 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-metadata.json?Expires=1710404160&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=LwT7wzrIgE%2FcGFjwezFoSv20HmJL2pjOGvKYtDWJTs3uC1NLUcAp2wFruouK6hOo5Ei%2FUyr%2B7bf8QiUHxRrEB%2F8sfPr7eO9Q%2B%2FAh9KxyirxX54mjQBD1OoAKk3oMA1WRYgl5vlvzYolZd2xZHtLL89r5TFN%2FTItohqhMu%2F7XoeeapNKt94IZWF%2BIU73QemCaY31Ex4RyDJ1gRu0ncH%2BpXWGl3gI1hLU7fl96UMtuQJZsgXCP1m4JjRsLTsLSkSeeY8RRf%2FU1cA3EdAmF%2FzipB8ahTgxNI8mkwrFwziJ7%2BsT69GjTxN7bzLiT46Vqh7iaUpOxy6VN2N09XWpwLQU0gg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3349CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:34,838 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:17:34,838 ERROR   wandb-upload_0:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:35,259 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:35,260 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:36,273 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:36,273 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:36,615 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/config.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HVX2YoirQiUedSI1%2BX53deOXw0ORGPgzUdqRug3538sm4XGLvbIHPQQQyXVCPWBXfCXEt0yv%2BbBoyX4vetxmYc6NE4I2%2FnOdB3ZjXdZfUrhCqWdid7Ar02T8GWCMjOj6SNdmQCbS6hjhopAg%2FhNuPDbH%2FBhFQNHg2JQAfibWRFEkUwBPHaBd9KWWovJsE58zkQ3PJcnzkl2%2F5vkeajrVCezbXXcb9NI3azJ854SOKWzP%2FVhDswXLzQI3MgtcsioQy%2F8HtT2%2FWVu3QfnIglsP%2FkaykhUEww%2Bu0WSLNx7rIKIZAl7Fm9b6yqv0leFaPLFA7sTK3YvBaw7wZJwY4T18rA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/config.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HVX2YoirQiUedSI1%2BX53deOXw0ORGPgzUdqRug3538sm4XGLvbIHPQQQyXVCPWBXfCXEt0yv%2BbBoyX4vetxmYc6NE4I2%2FnOdB3ZjXdZfUrhCqWdid7Ar02T8GWCMjOj6SNdmQCbS6hjhopAg%2FhNuPDbH%2FBhFQNHg2JQAfibWRFEkUwBPHaBd9KWWovJsE58zkQ3PJcnzkl2%2F5vkeajrVCezbXXcb9NI3azJ854SOKWzP%2FVhDswXLzQI3MgtcsioQy%2F8HtT2%2FWVu3QfnIglsP%2FkaykhUEww%2Bu0WSLNx7rIKIZAl7Fm9b6yqv0leFaPLFA7sTK3YvBaw7wZJwY4T18rA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3497040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:36,615 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 16:17:36,616 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:37,253 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/conda-environment.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n8dKo5LJaIo558EHQfxpFAMNJ5y%2FWvhnPIuMnfHjG9gxoNmlCIyNSHBdrwSovcXDZOBEx3WtO%2BIfbaxgCHP4ZQTU%2BBPWGtb1cwHz%2BbcqGCsL3pYrAB4CASfVk7eTZbmFNkZWNEevaH0buT6o14LJiebQa%2FgoYh%2BmUCzOe6E5qJ9HgXTZgsDjXaO%2FFj4sbgQwg4PKEyRpjAJ523GATy5fK0Tl0LY%2FpTRJc5LfV0xFOLXI6WeEfQBPmlotROk%2BAmU4xoGsr%2BsNdYRGzFDevhbIj%2FRoFRjWi1vx2lb6Se6p73XsHQn3AagtFKNsCuwVWLHe1UK5eHQC5UXtydavDGvMeg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/conda-environment.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n8dKo5LJaIo558EHQfxpFAMNJ5y%2FWvhnPIuMnfHjG9gxoNmlCIyNSHBdrwSovcXDZOBEx3WtO%2BIfbaxgCHP4ZQTU%2BBPWGtb1cwHz%2BbcqGCsL3pYrAB4CASfVk7eTZbmFNkZWNEevaH0buT6o14LJiebQa%2FgoYh%2BmUCzOe6E5qJ9HgXTZgsDjXaO%2FFj4sbgQwg4PKEyRpjAJ523GATy5fK0Tl0LY%2FpTRJc5LfV0xFOLXI6WeEfQBPmlotROk%2BAmU4xoGsr%2BsNdYRGzFDevhbIj%2FRoFRjWi1vx2lb6Se6p73XsHQn3AagtFKNsCuwVWLHe1UK5eHQC5UXtydavDGvMeg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3495E40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:37,254 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 16:17:37,254 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/requirements.txt?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gd9UXUPZjpM%2Fls50wYOrFMyWWAvmZkVL54JtM9%2BF2irdT9HnOxB7z9ItbF8GWj63X%2FuufQ5W0JAE%2B2WM9bHPYU13Rr0V61B%2BiCYXKab1j5bWwvqmnZ%2F6oi0TyZK8Glz%2BdUF5mUMKS3E4hluZ%2BSeAf%2BETDfIqMS6UGOmJsZwq4sHudWqeckAOtjoNP%2BjczjBXY2eL%2FJkgGnOg72txfbQ2VNP4T1gPHJIhgPUwR8GEtXz7MelxSmUbCNg8LHsUF6lBVRe6ubM90374C9V1pTlylT2kM0%2FheqANWZz3zHH8gRTYp%2B42wf9ecWBkYOePY9fOpvNDul2Jy8qLgfZQfJrY9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/requirements.txt?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gd9UXUPZjpM%2Fls50wYOrFMyWWAvmZkVL54JtM9%2BF2irdT9HnOxB7z9ItbF8GWj63X%2FuufQ5W0JAE%2B2WM9bHPYU13Rr0V61B%2BiCYXKab1j5bWwvqmnZ%2F6oi0TyZK8Glz%2BdUF5mUMKS3E4hluZ%2BSeAf%2BETDfIqMS6UGOmJsZwq4sHudWqeckAOtjoNP%2BjczjBXY2eL%2FJkgGnOg72txfbQ2VNP4T1gPHJIhgPUwR8GEtXz7MelxSmUbCNg8LHsUF6lBVRe6ubM90374C9V1pTlylT2kM0%2FheqANWZz3zHH8gRTYp%2B42wf9ecWBkYOePY9fOpvNDul2Jy8qLgfZQfJrY9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3494880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:37,254 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:37,254 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 16:17:37,254 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:37,275 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:37,275 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:37,614 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-summary.json?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c0fRQBa2mzx05958Ys2YkP%2BcLl4eZiLDNuCtcujds6PK%2B75vreCsPfHemeaagvg7RI4No%2Bl9oDOBVviPp9U7POVAalo8MJbwsAth6sI%2FOfadPEPYeOeosKmoTk%2B8bWy0Jkj2vGH4Tn96CmuhowtI3utNjV8d2w%2BKB34b9PwTU1K8%2F36MSsJOCGSyYOD5%2F7SHr9oHFmV5ebXH9%2B3ikJkZ06E71B9gVWlKpjcwgyz%2B%2BVicbkannUNkj9pu7gdtgUBcraNBMQrh%2BAxzQCqRB0cixHsRJm2mlUGMAUgKHzSde1Og8cfmb8i0eCnJThdXLyeAkyMIab4bwp1J9M4%2Bs5LcXg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-summary.json?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c0fRQBa2mzx05958Ys2YkP%2BcLl4eZiLDNuCtcujds6PK%2B75vreCsPfHemeaagvg7RI4No%2Bl9oDOBVviPp9U7POVAalo8MJbwsAth6sI%2FOfadPEPYeOeosKmoTk%2B8bWy0Jkj2vGH4Tn96CmuhowtI3utNjV8d2w%2BKB34b9PwTU1K8%2F36MSsJOCGSyYOD5%2F7SHr9oHFmV5ebXH9%2B3ikJkZ06E71B9gVWlKpjcwgyz%2B%2BVicbkannUNkj9pu7gdtgUBcraNBMQrh%2BAxzQCqRB0cixHsRJm2mlUGMAUgKHzSde1Og8cfmb8i0eCnJThdXLyeAkyMIab4bwp1J9M4%2Bs5LcXg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD34956C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:37,614 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/output.log?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=weqEq3kYehxVAV3HO5nWMECxnrlF%2BoEJ1E2DVTwFygQsj5ketv5vKZSYP6E9xkivLyn%2BX49vVflYQvqFpOiCVn44SQqJl5hgXGnDgi5k%2FIvsEMugSLnnxHxxenjQ87aZ4b9GOVEgBasZ%2FgsYwuvalwhacTQYDnIqkroSVOU3ex6LTQ4whUsSGHU89yBPWgKzujgdXz39%2FD1Sm2NuuzW4xbpvcfDDTMKA4z6Rta%2FAJA8PFo0ThbYSIF9OjP6AhR7DslYm7VeL37Up1z9VZKHNdiUFVpD5gF6ONsMIxMIs5SLHjDwANSIXW1qxLuC%2F9Vf2G6bCrKIZf2i%2BnNJ%2BAXJktw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/output.log?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=weqEq3kYehxVAV3HO5nWMECxnrlF%2BoEJ1E2DVTwFygQsj5ketv5vKZSYP6E9xkivLyn%2BX49vVflYQvqFpOiCVn44SQqJl5hgXGnDgi5k%2FIvsEMugSLnnxHxxenjQ87aZ4b9GOVEgBasZ%2FgsYwuvalwhacTQYDnIqkroSVOU3ex6LTQ4whUsSGHU89yBPWgKzujgdXz39%2FD1Sm2NuuzW4xbpvcfDDTMKA4z6Rta%2FAJA8PFo0ThbYSIF9OjP6AhR7DslYm7VeL37Up1z9VZKHNdiUFVpD5gF6ONsMIxMIs5SLHjDwANSIXW1qxLuC%2F9Vf2G6bCrKIZf2i%2BnNJ%2BAXJktw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD34961D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:37,614 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '204'}
2024-03-13 16:17:37,614 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1380'}
2024-03-13 16:17:37,614 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:37,615 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:38,276 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:38,277 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:38,277 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:39,278 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:39,278 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:40,293 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:40,294 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:41,308 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:41,308 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:42,311 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:42,312 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:43,325 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:43,326 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:43,326 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:44,339 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:44,340 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:45,346 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:45,346 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:46,354 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:46,355 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:47,355 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:47,356 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:48,174 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/config.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HVX2YoirQiUedSI1%2BX53deOXw0ORGPgzUdqRug3538sm4XGLvbIHPQQQyXVCPWBXfCXEt0yv%2BbBoyX4vetxmYc6NE4I2%2FnOdB3ZjXdZfUrhCqWdid7Ar02T8GWCMjOj6SNdmQCbS6hjhopAg%2FhNuPDbH%2FBhFQNHg2JQAfibWRFEkUwBPHaBd9KWWovJsE58zkQ3PJcnzkl2%2F5vkeajrVCezbXXcb9NI3azJ854SOKWzP%2FVhDswXLzQI3MgtcsioQy%2F8HtT2%2FWVu3QfnIglsP%2FkaykhUEww%2Bu0WSLNx7rIKIZAl7Fm9b6yqv0leFaPLFA7sTK3YvBaw7wZJwY4T18rA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/config.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HVX2YoirQiUedSI1%2BX53deOXw0ORGPgzUdqRug3538sm4XGLvbIHPQQQyXVCPWBXfCXEt0yv%2BbBoyX4vetxmYc6NE4I2%2FnOdB3ZjXdZfUrhCqWdid7Ar02T8GWCMjOj6SNdmQCbS6hjhopAg%2FhNuPDbH%2FBhFQNHg2JQAfibWRFEkUwBPHaBd9KWWovJsE58zkQ3PJcnzkl2%2F5vkeajrVCezbXXcb9NI3azJ854SOKWzP%2FVhDswXLzQI3MgtcsioQy%2F8HtT2%2FWVu3QfnIglsP%2FkaykhUEww%2Bu0WSLNx7rIKIZAl7Fm9b6yqv0leFaPLFA7sTK3YvBaw7wZJwY4T18rA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3497CA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:48,175 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 16:17:48,175 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:48,348 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/conda-environment.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n8dKo5LJaIo558EHQfxpFAMNJ5y%2FWvhnPIuMnfHjG9gxoNmlCIyNSHBdrwSovcXDZOBEx3WtO%2BIfbaxgCHP4ZQTU%2BBPWGtb1cwHz%2BbcqGCsL3pYrAB4CASfVk7eTZbmFNkZWNEevaH0buT6o14LJiebQa%2FgoYh%2BmUCzOe6E5qJ9HgXTZgsDjXaO%2FFj4sbgQwg4PKEyRpjAJ523GATy5fK0Tl0LY%2FpTRJc5LfV0xFOLXI6WeEfQBPmlotROk%2BAmU4xoGsr%2BsNdYRGzFDevhbIj%2FRoFRjWi1vx2lb6Se6p73XsHQn3AagtFKNsCuwVWLHe1UK5eHQC5UXtydavDGvMeg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/conda-environment.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n8dKo5LJaIo558EHQfxpFAMNJ5y%2FWvhnPIuMnfHjG9gxoNmlCIyNSHBdrwSovcXDZOBEx3WtO%2BIfbaxgCHP4ZQTU%2BBPWGtb1cwHz%2BbcqGCsL3pYrAB4CASfVk7eTZbmFNkZWNEevaH0buT6o14LJiebQa%2FgoYh%2BmUCzOe6E5qJ9HgXTZgsDjXaO%2FFj4sbgQwg4PKEyRpjAJ523GATy5fK0Tl0LY%2FpTRJc5LfV0xFOLXI6WeEfQBPmlotROk%2BAmU4xoGsr%2BsNdYRGzFDevhbIj%2FRoFRjWi1vx2lb6Se6p73XsHQn3AagtFKNsCuwVWLHe1UK5eHQC5UXtydavDGvMeg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3495540>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:48,348 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 16:17:48,348 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:48,370 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:48,371 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:48,371 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:48,857 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/requirements.txt?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gd9UXUPZjpM%2Fls50wYOrFMyWWAvmZkVL54JtM9%2BF2irdT9HnOxB7z9ItbF8GWj63X%2FuufQ5W0JAE%2B2WM9bHPYU13Rr0V61B%2BiCYXKab1j5bWwvqmnZ%2F6oi0TyZK8Glz%2BdUF5mUMKS3E4hluZ%2BSeAf%2BETDfIqMS6UGOmJsZwq4sHudWqeckAOtjoNP%2BjczjBXY2eL%2FJkgGnOg72txfbQ2VNP4T1gPHJIhgPUwR8GEtXz7MelxSmUbCNg8LHsUF6lBVRe6ubM90374C9V1pTlylT2kM0%2FheqANWZz3zHH8gRTYp%2B42wf9ecWBkYOePY9fOpvNDul2Jy8qLgfZQfJrY9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/requirements.txt?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gd9UXUPZjpM%2Fls50wYOrFMyWWAvmZkVL54JtM9%2BF2irdT9HnOxB7z9ItbF8GWj63X%2FuufQ5W0JAE%2B2WM9bHPYU13Rr0V61B%2BiCYXKab1j5bWwvqmnZ%2F6oi0TyZK8Glz%2BdUF5mUMKS3E4hluZ%2BSeAf%2BETDfIqMS6UGOmJsZwq4sHudWqeckAOtjoNP%2BjczjBXY2eL%2FJkgGnOg72txfbQ2VNP4T1gPHJIhgPUwR8GEtXz7MelxSmUbCNg8LHsUF6lBVRe6ubM90374C9V1pTlylT2kM0%2FheqANWZz3zHH8gRTYp%2B42wf9ecWBkYOePY9fOpvNDul2Jy8qLgfZQfJrY9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD0C910F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:48,857 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/output.log?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=weqEq3kYehxVAV3HO5nWMECxnrlF%2BoEJ1E2DVTwFygQsj5ketv5vKZSYP6E9xkivLyn%2BX49vVflYQvqFpOiCVn44SQqJl5hgXGnDgi5k%2FIvsEMugSLnnxHxxenjQ87aZ4b9GOVEgBasZ%2FgsYwuvalwhacTQYDnIqkroSVOU3ex6LTQ4whUsSGHU89yBPWgKzujgdXz39%2FD1Sm2NuuzW4xbpvcfDDTMKA4z6Rta%2FAJA8PFo0ThbYSIF9OjP6AhR7DslYm7VeL37Up1z9VZKHNdiUFVpD5gF6ONsMIxMIs5SLHjDwANSIXW1qxLuC%2F9Vf2G6bCrKIZf2i%2BnNJ%2BAXJktw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/output.log?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=weqEq3kYehxVAV3HO5nWMECxnrlF%2BoEJ1E2DVTwFygQsj5ketv5vKZSYP6E9xkivLyn%2BX49vVflYQvqFpOiCVn44SQqJl5hgXGnDgi5k%2FIvsEMugSLnnxHxxenjQ87aZ4b9GOVEgBasZ%2FgsYwuvalwhacTQYDnIqkroSVOU3ex6LTQ4whUsSGHU89yBPWgKzujgdXz39%2FD1Sm2NuuzW4xbpvcfDDTMKA4z6Rta%2FAJA8PFo0ThbYSIF9OjP6AhR7DslYm7VeL37Up1z9VZKHNdiUFVpD5gF6ONsMIxMIs5SLHjDwANSIXW1qxLuC%2F9Vf2G6bCrKIZf2i%2BnNJ%2BAXJktw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD0C914E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:48,857 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 16:17:48,857 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1380'}
2024-03-13 16:17:48,857 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:48,857 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:49,016 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-summary.json?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c0fRQBa2mzx05958Ys2YkP%2BcLl4eZiLDNuCtcujds6PK%2B75vreCsPfHemeaagvg7RI4No%2Bl9oDOBVviPp9U7POVAalo8MJbwsAth6sI%2FOfadPEPYeOeosKmoTk%2B8bWy0Jkj2vGH4Tn96CmuhowtI3utNjV8d2w%2BKB34b9PwTU1K8%2F36MSsJOCGSyYOD5%2F7SHr9oHFmV5ebXH9%2B3ikJkZ06E71B9gVWlKpjcwgyz%2B%2BVicbkannUNkj9pu7gdtgUBcraNBMQrh%2BAxzQCqRB0cixHsRJm2mlUGMAUgKHzSde1Og8cfmb8i0eCnJThdXLyeAkyMIab4bwp1J9M4%2Bs5LcXg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-summary.json?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c0fRQBa2mzx05958Ys2YkP%2BcLl4eZiLDNuCtcujds6PK%2B75vreCsPfHemeaagvg7RI4No%2Bl9oDOBVviPp9U7POVAalo8MJbwsAth6sI%2FOfadPEPYeOeosKmoTk%2B8bWy0Jkj2vGH4Tn96CmuhowtI3utNjV8d2w%2BKB34b9PwTU1K8%2F36MSsJOCGSyYOD5%2F7SHr9oHFmV5ebXH9%2B3ikJkZ06E71B9gVWlKpjcwgyz%2B%2BVicbkannUNkj9pu7gdtgUBcraNBMQrh%2BAxzQCqRB0cixHsRJm2mlUGMAUgKHzSde1Og8cfmb8i0eCnJThdXLyeAkyMIab4bwp1J9M4%2Bs5LcXg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD0C916F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:17:49,016 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '204'}
2024-03-13 16:17:49,016 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:17:49,373 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:49,374 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:50,381 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:50,382 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:51,389 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:51,389 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:52,390 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:52,391 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:53,393 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:53,394 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:53,394 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:54,395 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:54,396 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:55,410 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:55,411 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:56,424 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:56,425 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:57,425 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:57,425 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:58,438 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:58,438 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:17:58,439 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:17:59,442 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:17:59,443 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:00,213 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/config.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HVX2YoirQiUedSI1%2BX53deOXw0ORGPgzUdqRug3538sm4XGLvbIHPQQQyXVCPWBXfCXEt0yv%2BbBoyX4vetxmYc6NE4I2%2FnOdB3ZjXdZfUrhCqWdid7Ar02T8GWCMjOj6SNdmQCbS6hjhopAg%2FhNuPDbH%2FBhFQNHg2JQAfibWRFEkUwBPHaBd9KWWovJsE58zkQ3PJcnzkl2%2F5vkeajrVCezbXXcb9NI3azJ854SOKWzP%2FVhDswXLzQI3MgtcsioQy%2F8HtT2%2FWVu3QfnIglsP%2FkaykhUEww%2Bu0WSLNx7rIKIZAl7Fm9b6yqv0leFaPLFA7sTK3YvBaw7wZJwY4T18rA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/config.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HVX2YoirQiUedSI1%2BX53deOXw0ORGPgzUdqRug3538sm4XGLvbIHPQQQyXVCPWBXfCXEt0yv%2BbBoyX4vetxmYc6NE4I2%2FnOdB3ZjXdZfUrhCqWdid7Ar02T8GWCMjOj6SNdmQCbS6hjhopAg%2FhNuPDbH%2FBhFQNHg2JQAfibWRFEkUwBPHaBd9KWWovJsE58zkQ3PJcnzkl2%2F5vkeajrVCezbXXcb9NI3azJ854SOKWzP%2FVhDswXLzQI3MgtcsioQy%2F8HtT2%2FWVu3QfnIglsP%2FkaykhUEww%2Bu0WSLNx7rIKIZAl7Fm9b6yqv0leFaPLFA7sTK3YvBaw7wZJwY4T18rA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3497940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:18:00,214 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 16:18:00,214 ERROR   wandb-upload_2:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:18:00,445 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:00,445 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:00,853 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-summary.json?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c0fRQBa2mzx05958Ys2YkP%2BcLl4eZiLDNuCtcujds6PK%2B75vreCsPfHemeaagvg7RI4No%2Bl9oDOBVviPp9U7POVAalo8MJbwsAth6sI%2FOfadPEPYeOeosKmoTk%2B8bWy0Jkj2vGH4Tn96CmuhowtI3utNjV8d2w%2BKB34b9PwTU1K8%2F36MSsJOCGSyYOD5%2F7SHr9oHFmV5ebXH9%2B3ikJkZ06E71B9gVWlKpjcwgyz%2B%2BVicbkannUNkj9pu7gdtgUBcraNBMQrh%2BAxzQCqRB0cixHsRJm2mlUGMAUgKHzSde1Og8cfmb8i0eCnJThdXLyeAkyMIab4bwp1J9M4%2Bs5LcXg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/wandb-summary.json?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c0fRQBa2mzx05958Ys2YkP%2BcLl4eZiLDNuCtcujds6PK%2B75vreCsPfHemeaagvg7RI4No%2Bl9oDOBVviPp9U7POVAalo8MJbwsAth6sI%2FOfadPEPYeOeosKmoTk%2B8bWy0Jkj2vGH4Tn96CmuhowtI3utNjV8d2w%2BKB34b9PwTU1K8%2F36MSsJOCGSyYOD5%2F7SHr9oHFmV5ebXH9%2B3ikJkZ06E71B9gVWlKpjcwgyz%2B%2BVicbkannUNkj9pu7gdtgUBcraNBMQrh%2BAxzQCqRB0cixHsRJm2mlUGMAUgKHzSde1Og8cfmb8i0eCnJThdXLyeAkyMIab4bwp1J9M4%2Bs5LcXg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3497F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:18:00,853 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/conda-environment.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n8dKo5LJaIo558EHQfxpFAMNJ5y%2FWvhnPIuMnfHjG9gxoNmlCIyNSHBdrwSovcXDZOBEx3WtO%2BIfbaxgCHP4ZQTU%2BBPWGtb1cwHz%2BbcqGCsL3pYrAB4CASfVk7eTZbmFNkZWNEevaH0buT6o14LJiebQa%2FgoYh%2BmUCzOe6E5qJ9HgXTZgsDjXaO%2FFj4sbgQwg4PKEyRpjAJ523GATy5fK0Tl0LY%2FpTRJc5LfV0xFOLXI6WeEfQBPmlotROk%2BAmU4xoGsr%2BsNdYRGzFDevhbIj%2FRoFRjWi1vx2lb6Se6p73XsHQn3AagtFKNsCuwVWLHe1UK5eHQC5UXtydavDGvMeg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/conda-environment.yaml?Expires=1710404249&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=n8dKo5LJaIo558EHQfxpFAMNJ5y%2FWvhnPIuMnfHjG9gxoNmlCIyNSHBdrwSovcXDZOBEx3WtO%2BIfbaxgCHP4ZQTU%2BBPWGtb1cwHz%2BbcqGCsL3pYrAB4CASfVk7eTZbmFNkZWNEevaH0buT6o14LJiebQa%2FgoYh%2BmUCzOe6E5qJ9HgXTZgsDjXaO%2FFj4sbgQwg4PKEyRpjAJ523GATy5fK0Tl0LY%2FpTRJc5LfV0xFOLXI6WeEfQBPmlotROk%2BAmU4xoGsr%2BsNdYRGzFDevhbIj%2FRoFRjWi1vx2lb6Se6p73XsHQn3AagtFKNsCuwVWLHe1UK5eHQC5UXtydavDGvMeg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3495630>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:18:00,853 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/output.log?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=weqEq3kYehxVAV3HO5nWMECxnrlF%2BoEJ1E2DVTwFygQsj5ketv5vKZSYP6E9xkivLyn%2BX49vVflYQvqFpOiCVn44SQqJl5hgXGnDgi5k%2FIvsEMugSLnnxHxxenjQ87aZ4b9GOVEgBasZ%2FgsYwuvalwhacTQYDnIqkroSVOU3ex6LTQ4whUsSGHU89yBPWgKzujgdXz39%2FD1Sm2NuuzW4xbpvcfDDTMKA4z6Rta%2FAJA8PFo0ThbYSIF9OjP6AhR7DslYm7VeL37Up1z9VZKHNdiUFVpD5gF6ONsMIxMIs5SLHjDwANSIXW1qxLuC%2F9Vf2G6bCrKIZf2i%2BnNJ%2BAXJktw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/output.log?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=weqEq3kYehxVAV3HO5nWMECxnrlF%2BoEJ1E2DVTwFygQsj5ketv5vKZSYP6E9xkivLyn%2BX49vVflYQvqFpOiCVn44SQqJl5hgXGnDgi5k%2FIvsEMugSLnnxHxxenjQ87aZ4b9GOVEgBasZ%2FgsYwuvalwhacTQYDnIqkroSVOU3ex6LTQ4whUsSGHU89yBPWgKzujgdXz39%2FD1Sm2NuuzW4xbpvcfDDTMKA4z6Rta%2FAJA8PFo0ThbYSIF9OjP6AhR7DslYm7VeL37Up1z9VZKHNdiUFVpD5gF6ONsMIxMIs5SLHjDwANSIXW1qxLuC%2F9Vf2G6bCrKIZf2i%2BnNJ%2BAXJktw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD3494550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:18:00,854 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '204'}
2024-03-13 16:18:00,854 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 16:18:00,854 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1380'}
2024-03-13 16:18:00,854 ERROR   wandb-upload_5:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:18:00,854 ERROR   wandb-upload_1:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:18:00,854 ERROR   wandb-upload_3:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:18:01,094 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/requirements.txt?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gd9UXUPZjpM%2Fls50wYOrFMyWWAvmZkVL54JtM9%2BF2irdT9HnOxB7z9ItbF8GWj63X%2FuufQ5W0JAE%2B2WM9bHPYU13Rr0V61B%2BiCYXKab1j5bWwvqmnZ%2F6oi0TyZK8Glz%2BdUF5mUMKS3E4hluZ%2BSeAf%2BETDfIqMS6UGOmJsZwq4sHudWqeckAOtjoNP%2BjczjBXY2eL%2FJkgGnOg72txfbQ2VNP4T1gPHJIhgPUwR8GEtXz7MelxSmUbCNg8LHsUF6lBVRe6ubM90374C9V1pTlylT2kM0%2FheqANWZz3zHH8gRTYp%2B42wf9ecWBkYOePY9fOpvNDul2Jy8qLgfZQfJrY9A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/yw706lp8/requirements.txt?Expires=1710404250&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gd9UXUPZjpM%2Fls50wYOrFMyWWAvmZkVL54JtM9%2BF2irdT9HnOxB7z9ItbF8GWj63X%2FuufQ5W0JAE%2B2WM9bHPYU13Rr0V61B%2BiCYXKab1j5bWwvqmnZ%2F6oi0TyZK8Glz%2BdUF5mUMKS3E4hluZ%2BSeAf%2BETDfIqMS6UGOmJsZwq4sHudWqeckAOtjoNP%2BjczjBXY2eL%2FJkgGnOg72txfbQ2VNP4T1gPHJIhgPUwR8GEtXz7MelxSmUbCNg8LHsUF6lBVRe6ubM90374C9V1pTlylT2kM0%2FheqANWZz3zHH8gRTYp%2B42wf9ecWBkYOePY9fOpvNDul2Jy8qLgfZQfJrY9A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027BD34954B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:18:01,094 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 16:18:01,094 ERROR   wandb-upload_4:19860 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:18:01,460 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:01,461 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:02,463 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:02,463 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:03,471 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:03,471 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:03,471 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:04,473 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:04,474 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:05,486 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:05,486 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:06,487 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:06,487 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:18:07,494 DEBUG   HandlerThread:19860 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:18:07,495 DEBUG   SenderThread:19860 [sender.py:send_request():407] send_request: poll_exit
