2024-03-13 20:46:22,132 INFO    StreamThr :28992 [internal.py:wandb_internal():86] W&B internal server running at pid: 28992, started at: 2024-03-13 20:46:22.131040
2024-03-13 20:46:22,133 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status
2024-03-13 20:46:22,138 INFO    WriterThread:28992 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\run-cdqyb3ac.wandb
2024-03-13 20:46:22,140 DEBUG   SenderThread:28992 [sender.py:send():380] send: header
2024-03-13 20:46:22,140 DEBUG   SenderThread:28992 [sender.py:send():380] send: run
2024-03-13 20:46:24,331 INFO    SenderThread:28992 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files
2024-03-13 20:46:24,332 INFO    SenderThread:28992 [sender.py:_start_run_threads():1122] run started: cdqyb3ac with start time 1710333982.13204
2024-03-13 20:46:24,350 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 20:46:24,350 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: check_version
2024-03-13 20:46:27,066 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 20:46:27,112 DEBUG   HandlerThread:28992 [system_info.py:__init__():32] System info init
2024-03-13 20:46:27,112 DEBUG   HandlerThread:28992 [system_info.py:__init__():47] System info init done
2024-03-13 20:46:27,112 INFO    HandlerThread:28992 [system_monitor.py:start():181] Starting system monitor
2024-03-13 20:46:27,112 INFO    SystemMonitor:28992 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 20:46:27,112 INFO    HandlerThread:28992 [system_monitor.py:probe():201] Collecting system info
2024-03-13 20:46:27,118 INFO    SystemMonitor:28992 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 20:46:27,118 INFO    SystemMonitor:28992 [interfaces.py:start():190] Started disk monitoring
2024-03-13 20:46:27,119 INFO    SystemMonitor:28992 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 20:46:27,120 INFO    SystemMonitor:28992 [interfaces.py:start():190] Started memory monitoring
2024-03-13 20:46:27,136 INFO    SystemMonitor:28992 [interfaces.py:start():190] Started network monitoring
2024-03-13 20:46:27,162 DEBUG   HandlerThread:28992 [system_info.py:probe():196] Probing system
2024-03-13 20:46:27,162 DEBUG   HandlerThread:28992 [system_info.py:probe():244] Probing system done
2024-03-13 20:46:27,162 DEBUG   HandlerThread:28992 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T12:46:27.162809', 'startedAt': '2024-03-13T12:46:22.118046', 'docker': None, 'cuda': None, 'args': ('--task=P', '--weather=foggy'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 178.9093360900879}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 20:46:27,162 INFO    HandlerThread:28992 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 20:46:27,162 INFO    HandlerThread:28992 [system_monitor.py:probe():214] Publishing system info
2024-03-13 20:46:27,162 DEBUG   HandlerThread:28992 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 20:46:27,163 DEBUG   HandlerThread:28992 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 20:46:27,163 DEBUG   HandlerThread:28992 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 20:46:27,177 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:27,355 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\requirements.txt
2024-03-13 20:46:27,355 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\conda-environment.yaml
2024-03-13 20:46:29,216 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:31,255 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:33,283 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:34,131 DEBUG   HandlerThread:28992 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 20:46:34,132 INFO    HandlerThread:28992 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 20:46:34,152 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:46:34,152 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:46:34,152 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:46:34,153 DEBUG   SenderThread:28992 [sender.py:send():380] send: files
2024-03-13 20:46:34,153 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 20:46:34,164 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:46:34,164 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:46:34,166 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:46:34,416 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\conda-environment.yaml
2024-03-13 20:46:34,416 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-metadata.json
2024-03-13 20:46:34,900 DEBUG   SenderThread:28992 [sender.py:send():380] send: telemetry
2024-03-13 20:46:35,314 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:35,421 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:37,354 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:37,431 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:38,937 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:46:39,390 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:41,090 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:41,091 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:41,092 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:41,093 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:41,426 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:41,490 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:42,834 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:42,835 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:42,836 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:42,836 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:42,837 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:42,838 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:42,838 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:42,838 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:43,463 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:43,506 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:43,507 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:44,847 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:46:45,496 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:45,514 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:46,735 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:46,736 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:46,736 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:46,737 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:46,940 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002724956DD50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:46:46,940 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1320'}
2024-03-13 20:46:46,940 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:46:47,529 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:47,545 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:48,451 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:48,451 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:48,452 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:48,453 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:48,453 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:48,454 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:48,454 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:48,455 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:48,549 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:49,172 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:46:49,172 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:46:49,172 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:46:49,554 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:49,572 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:50,523 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:46:51,605 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:52,394 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:52,395 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:52,395 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:52,396 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:52,607 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:53,628 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:53,644 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:54,094 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:54,095 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:54,095 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:54,096 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:54,097 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:54,097 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:54,097 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:54,098 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:54,635 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:55,668 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:55,684 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:56,122 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:46:56,677 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\config.yaml
2024-03-13 20:46:57,780 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:46:58,019 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:58,020 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:58,020 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:58,021 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:58,735 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:46:59,755 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:46:59,784 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:59,785 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:46:59,785 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:59,786 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:59,787 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:59,787 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:46:59,787 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:46:59,788 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:46:59,808 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:00,601 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002724961B520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:47:00,601 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1320'}
2024-03-13 20:47:00,601 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:47:00,762 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:01,783 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:01,800 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:01,838 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:03,687 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:03,687 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:03,688 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:03,689 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:03,821 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:03,859 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:04,174 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:47:04,175 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:47:04,175 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:47:05,404 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:05,405 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:05,405 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:05,406 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:05,406 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:05,407 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:05,407 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:05,408 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:05,858 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:05,858 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:05,878 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:07,428 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:07,887 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:07,907 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:09,290 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:09,290 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:09,291 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:09,292 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:09,922 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:09,940 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:11,025 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:11,026 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:11,026 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:11,027 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:11,028 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:11,028 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:11,028 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:11,029 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:11,963 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:11,964 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:11,980 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:13,033 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:14,003 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:14,020 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:14,927 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:14,928 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:14,928 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:14,929 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:15,013 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:16,060 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:16,096 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C0910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:47:16,096 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1320'}
2024-03-13 20:47:16,096 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:47:16,096 INFO    wandb-upload_0:28992 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000272496C0910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C0910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C0910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 20:47:16,631 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:16,632 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:16,632 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:16,633 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:16,634 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:16,634 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:16,635 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:16,635 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:17,053 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:18,073 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:18,098 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:18,648 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:19,190 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:47:19,190 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:47:19,191 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:47:20,136 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:20,547 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:20,548 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:20,548 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:20,549 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:21,121 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:21,122 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:22,173 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:22,256 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:22,257 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:22,258 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:22,258 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:22,259 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:22,259 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:22,259 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:22,260 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:23,165 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:23,166 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:24,205 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:24,284 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:26,152 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:26,153 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:26,153 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:26,154 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:26,228 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:26,244 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:27,158 DEBUG   SystemMonitor:28992 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 20:47:27,159 DEBUG   SenderThread:28992 [sender.py:send():380] send: stats
2024-03-13 20:47:27,239 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:27,907 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:27,908 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:27,909 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:27,909 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:27,910 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:27,910 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:27,911 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:27,911 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:28,274 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:28,340 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:29,276 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:29,927 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:30,376 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:31,818 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:31,819 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:31,819 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:31,821 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:32,343 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:32,395 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:32,828 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002724961B3D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:47:32,828 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1320'}
2024-03-13 20:47:32,828 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:47:33,348 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:33,531 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:33,532 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:33,532 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:33,533 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:33,533 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:33,534 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:33,534 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:33,535 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:34,193 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:47:34,209 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:47:34,210 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:47:34,380 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:34,418 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:35,390 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:35,788 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:36,448 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:37,441 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:37,442 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:37,442 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:37,443 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:38,451 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:38,469 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:39,150 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:39,151 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:39,152 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:39,152 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:39,153 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:39,153 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:39,154 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:39,154 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:39,456 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:39,457 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:40,508 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:41,160 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:41,497 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:42,546 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:43,067 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:43,068 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:43,068 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:43,069 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:43,537 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:44,578 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:44,772 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:44,773 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:44,774 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:44,774 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:44,775 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:44,775 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:44,776 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:44,776 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:45,566 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:45,566 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:46,623 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:46,796 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:47,610 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:48,657 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:48,671 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:48,671 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:48,672 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:48,672 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:49,204 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:47:49,219 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:47:49,220 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:47:49,652 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:49,653 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:50,411 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:50,411 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:50,412 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:50,413 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:50,413 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:50,414 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:50,414 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:50,415 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:50,670 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:50,687 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:51,681 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:52,431 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:52,726 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:54,313 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:54,313 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:54,314 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:54,315 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:54,733 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:54,753 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:55,739 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:56,047 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:56,048 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:47:56,048 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:56,049 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:56,050 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:56,050 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:47:56,050 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:47:56,051 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:47:56,774 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:47:56,792 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:47:57,170 DEBUG   SenderThread:28992 [sender.py:send():380] send: stats
2024-03-13 20:47:57,786 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:47:58,182 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:47:58,888 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:00,182 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:00,183 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:00,183 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:00,184 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:00,402 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002724961A590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:00,402 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1320'}
2024-03-13 20:48:00,402 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:00,843 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:00,910 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:01,858 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:01,956 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:01,957 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:01,958 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:01,958 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:01,959 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:01,959 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:01,959 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:01,960 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:02,886 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:02,941 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:03,901 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:03,978 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:04,203 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:48:04,217 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:48:04,218 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:48:04,968 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:05,944 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:05,945 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:05,945 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:05,946 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:06,955 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:06,996 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:07,722 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:07,723 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:07,723 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:07,724 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:07,725 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:07,725 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:07,725 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:07,726 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:07,965 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:07,966 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:09,028 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:09,756 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:09,996 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:11,053 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:11,666 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:11,667 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:11,667 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:11,668 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:12,039 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:13,080 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:13,427 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:13,428 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:13,428 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:13,429 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:13,430 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:13,430 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:13,430 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:13,431 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:14,070 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:14,071 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:15,116 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:15,443 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:16,099 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:17,139 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:17,335 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:17,336 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:17,336 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:17,337 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:18,126 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:19,052 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:19,053 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:19,054 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:19,054 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:19,055 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:19,056 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:19,056 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:19,056 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:19,157 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:19,176 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:19,192 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:48:19,209 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:48:19,209 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:48:20,164 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:21,212 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:21,224 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:22,194 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:22,963 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:22,964 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:22,964 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:22,965 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:23,232 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:23,254 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:24,672 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:24,673 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:24,674 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:24,674 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:24,675 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:24,676 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:24,676 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:24,676 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:25,272 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:25,292 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:26,281 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:26,694 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:27,174 DEBUG   SenderThread:28992 [sender.py:send():380] send: stats
2024-03-13 20:48:27,334 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:28,581 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:28,582 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:28,582 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:28,583 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:29,358 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:29,415 ERROR   gpu       :28992 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:48:30,346 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:30,347 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:48:30,348 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:30,348 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:30,349 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:30,349 DEBUG   SenderThread:28992 [sender.py:send():380] send: history
2024-03-13 20:48:30,349 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:48:30,350 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:30,369 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:30,370 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:30,493 DEBUG   SenderThread:28992 [sender.py:send():380] send: exit
2024-03-13 20:48:30,493 INFO    SenderThread:28992 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 20:48:30,493 INFO    SenderThread:28992 [sender.py:send_exit():587] handling runtime: 123
2024-03-13 20:48:30,494 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:30,494 INFO    SenderThread:28992 [sender.py:send_exit():593] send defer
2024-03-13 20:48:30,494 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,494 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 20:48:30,495 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,495 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 20:48:30,495 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 1
2024-03-13 20:48:30,495 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,495 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 20:48:30,495 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,495 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 20:48:30,495 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 2
2024-03-13 20:48:30,495 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,496 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 20:48:30,496 INFO    HandlerThread:28992 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 20:48:30,496 DEBUG   SystemMonitor:28992 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 20:48:30,502 INFO    HandlerThread:28992 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 20:48:30,503 DEBUG   SystemMonitor:28992 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 20:48:30,503 INFO    HandlerThread:28992 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 20:48:30,541 INFO    HandlerThread:28992 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 20:48:30,541 INFO    HandlerThread:28992 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 20:48:30,541 INFO    HandlerThread:28992 [interfaces.py:finish():202] Joined network monitor
2024-03-13 20:48:30,542 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,542 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 20:48:30,542 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 3
2024-03-13 20:48:30,543 DEBUG   SenderThread:28992 [sender.py:send():380] send: stats
2024-03-13 20:48:30,543 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,543 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 20:48:30,543 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,543 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 20:48:30,543 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 4
2024-03-13 20:48:30,544 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,544 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 20:48:30,544 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,544 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 20:48:30,544 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 5
2024-03-13 20:48:30,544 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,544 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 20:48:30,545 DEBUG   SenderThread:28992 [sender.py:send():380] send: summary
2024-03-13 20:48:30,545 INFO    SenderThread:28992 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:48:30,546 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,546 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 20:48:30,546 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 6
2024-03-13 20:48:30,546 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,546 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 20:48:30,546 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,546 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 20:48:30,546 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 7
2024-03-13 20:48:30,546 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:30,547 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:30,547 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 20:48:30,547 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:30,547 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 20:48:31,374 INFO    Thread-12 :28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json
2024-03-13 20:48:31,405 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 8
2024-03-13 20:48:31,405 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:31,405 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 20:48:31,405 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:31,405 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 20:48:31,405 INFO    SenderThread:28992 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 20:48:31,406 INFO    SenderThread:28992 [job_builder.py:_get_source_type():404] no source found
2024-03-13 20:48:31,406 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 9
2024-03-13 20:48:31,407 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:31,407 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 20:48:31,407 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:31,407 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 20:48:31,407 INFO    SenderThread:28992 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 20:48:31,497 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:32,391 INFO    SenderThread:28992 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log
2024-03-13 20:48:32,392 INFO    SenderThread:28992 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files
2024-03-13 20:48:32,393 INFO    SenderThread:28992 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\conda-environment.yaml conda-environment.yaml
2024-03-13 20:48:32,394 INFO    SenderThread:28992 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\config.yaml config.yaml
2024-03-13 20:48:32,396 INFO    SenderThread:28992 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\output.log output.log
2024-03-13 20:48:32,398 INFO    SenderThread:28992 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\requirements.txt requirements.txt
2024-03-13 20:48:32,400 INFO    SenderThread:28992 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-metadata.json wandb-metadata.json
2024-03-13 20:48:32,400 INFO    SenderThread:28992 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204622-cdqyb3ac\files\wandb-summary.json wandb-summary.json
2024-03-13 20:48:32,402 INFO    SenderThread:28992 [sender.py:transition_state():613] send defer: 10
2024-03-13 20:48:32,403 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:32,403 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:48:32,403 INFO    HandlerThread:28992 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 20:48:32,405 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: defer
2024-03-13 20:48:32,405 INFO    SenderThread:28992 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 20:48:32,405 INFO    SenderThread:28992 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 20:48:32,500 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:32,500 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:32,687 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-metadata.json?Expires=1710420397&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mzdPryEAi6qL4eZLBOWKbfu51ABUvcN8pctnHpuQoOTx%2BPMNH4oblXv2WjUnf2WgHZTpi8W4Qz%2BRi9AXqtdhPWqP1R61mP1BkLrb1YUIc2I7j7m5hnpD9g0mey%2Bw8%2FNvXEX%2Fus7XdoZS1WtQVzHaCIJzrKg2gVqmXUUcTSQB%2FgSAGqqqV%2Bw12rWsDcL3OvxW66ErV0IgBOaehMzptq8JVbJiU6uK1EIsRh%2Fgk1qleEA4wICS39ACgtg1H5hRKE8aMcSyt8ohtaUZOY464BOBLM3pj%2Bp9GqXUr5RNvDcM4tG4L8GDtuCt9I5MnkwbK74P8DIM6RmKlAnjMiPJblnjHA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C2740>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:32,687 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1320'}
2024-03-13 20:48:32,687 ERROR   wandb-upload_0:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:33,503 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:33,504 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:34,514 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:34,515 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:35,519 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:35,519 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:36,532 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:36,533 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:37,539 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:37,540 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:37,540 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:38,544 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:38,545 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:39,560 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:39,560 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:40,562 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:40,562 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:41,562 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:41,563 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:42,567 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:42,567 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:42,568 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:43,569 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:43,570 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:44,582 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:44,582 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:44,938 ERROR   wandb-upload_1:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/conda-environment.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sLEV83xl3mwdqsozBHCh22ULXbGNvjggri7N%2BLE2qZMZHGIFPBKFwyfLyWYlLigPAz1eispLKBgzdSiT3uScr2p3jMZWqYcUrtHfsNWX%2FLn0dKXnKOWtw06Wc2%2FuX4%2B79jjIRQJ3c7BhT9wMiaX6BrWDGDWgZbxpwirtuh1i8%2BnrQh5143cS8MLCC5oF62wumPdCIXhjVnn7QLJocPhYewc8LM2OYck%2FOeew6L9Eb56gu5LHKslRg0KKIOIKwKyv0pKiQw9gUJNUN%2BuuDCZ4wLSNgg8fTa%2Bptw26LJNGReempMr29ChCi2LDccqxaLRZJdh%2BhDn%2BSYsWtcOZL0bGBQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/conda-environment.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sLEV83xl3mwdqsozBHCh22ULXbGNvjggri7N%2BLE2qZMZHGIFPBKFwyfLyWYlLigPAz1eispLKBgzdSiT3uScr2p3jMZWqYcUrtHfsNWX%2FLn0dKXnKOWtw06Wc2%2FuX4%2B79jjIRQJ3c7BhT9wMiaX6BrWDGDWgZbxpwirtuh1i8%2BnrQh5143cS8MLCC5oF62wumPdCIXhjVnn7QLJocPhYewc8LM2OYck%2FOeew6L9Eb56gu5LHKslRg0KKIOIKwKyv0pKiQw9gUJNUN%2BuuDCZ4wLSNgg8fTa%2Bptw26LJNGReempMr29ChCi2LDccqxaLRZJdh%2BhDn%2BSYsWtcOZL0bGBQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C3700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:44,938 ERROR   wandb-upload_1:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:48:44,938 ERROR   wandb-upload_1:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:45,220 ERROR   wandb-upload_2:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/config.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZV91a4UbdwfcdaOFCYo6FLPD9HgLKJb17iIQa%2B57VNynILBJ86qZswjYnzKplF7%2FEkQnN4j6P6xdSKkpj%2Fv5ObYrkRdt23Vguz2KszT%2Bau%2BuHRXx6aFmdggDIBrM1g%2FqSZ%2FxbcuHWB8rx9lU51fx7Rs4eBoBmsvsn3FOoyuQ9j%2FAcxziWMUAnT%2BhDSGjcSAmiZxwUZ1VpykBBQ2J6ZXQ6jEKQiUYVTqr7W3Yp0Amvz0ih8BwLKdriDSiCBtWaUf2LUq9bp987uGCzFaWBZH2VOUvSOp8kO%2BmvpRxg3WUnHjaw0mTQekwMkbPI4%2BRoCqcmdC67vrJGWzyRLXv%2FzMVWA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/config.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZV91a4UbdwfcdaOFCYo6FLPD9HgLKJb17iIQa%2B57VNynILBJ86qZswjYnzKplF7%2FEkQnN4j6P6xdSKkpj%2Fv5ObYrkRdt23Vguz2KszT%2Bau%2BuHRXx6aFmdggDIBrM1g%2FqSZ%2FxbcuHWB8rx9lU51fx7Rs4eBoBmsvsn3FOoyuQ9j%2FAcxziWMUAnT%2BhDSGjcSAmiZxwUZ1VpykBBQ2J6ZXQ6jEKQiUYVTqr7W3Yp0Amvz0ih8BwLKdriDSiCBtWaUf2LUq9bp987uGCzFaWBZH2VOUvSOp8kO%2BmvpRxg3WUnHjaw0mTQekwMkbPI4%2BRoCqcmdC67vrJGWzyRLXv%2FzMVWA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C0580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:45,220 ERROR   wandb-upload_3:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/output.log?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QvDbmTRMgBIrJfJDnPI0SJ2kCCIv8zovp1jVvKxIYiiqhDwYG%2BuwUn9CcXbICchIDiA0PmprBvWc9ODqhqaoI5fgPrMoSqwANEypfy%2B72uEKjeQ1Z%2FjRsYw%2Fpn9aYNahx1cVlXv%2B2JOAjvXgLT5QuekJLa%2FVP%2FPcy4iFKgyPf0Y5NFh3E7Z%2F3kgO9AxMsl%2FjsN2HQFGeYdjNmGWHVbcAtNHGOXn0r2T5ZszHmgAGR4WJLnWI1L6vzAW%2BQelTeaFtJyna7gQND%2FVstKGu31z9BPrPXWs4r2mnMttw2IjdKbn8Lka7H%2BYEcMPRszzQU30AIxcLVoc%2Fl1bevi75Pzu%2Btg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/output.log?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QvDbmTRMgBIrJfJDnPI0SJ2kCCIv8zovp1jVvKxIYiiqhDwYG%2BuwUn9CcXbICchIDiA0PmprBvWc9ODqhqaoI5fgPrMoSqwANEypfy%2B72uEKjeQ1Z%2FjRsYw%2Fpn9aYNahx1cVlXv%2B2JOAjvXgLT5QuekJLa%2FVP%2FPcy4iFKgyPf0Y5NFh3E7Z%2F3kgO9AxMsl%2FjsN2HQFGeYdjNmGWHVbcAtNHGOXn0r2T5ZszHmgAGR4WJLnWI1L6vzAW%2BQelTeaFtJyna7gQND%2FVstKGu31z9BPrPXWs4r2mnMttw2IjdKbn8Lka7H%2BYEcMPRszzQU30AIxcLVoc%2Fl1bevi75Pzu%2Btg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C3430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:45,220 ERROR   wandb-upload_2:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '455'}
2024-03-13 20:48:45,220 ERROR   wandb-upload_3:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1442'}
2024-03-13 20:48:45,220 ERROR   wandb-upload_2:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:45,220 ERROR   wandb-upload_3:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:45,583 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:45,583 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:46,408 ERROR   wandb-upload_4:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/requirements.txt?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NOeCLeBUfWovhkdc4OY4GlFWJ3EnmIOGS4uox7oxQ5pzDRR6e1ary1FBYMQlIk0Qk3oi6T5wx80ajdhKkb4zF6BZHVBa41%2BMkKmEHdi3Xu9bchaVerJRjJO27PyXrXof0LbO6qmmqmiQBBAtaXk%2BUI7PHI5Sekk5E23Org3p42eKNH0ehOxcj9Q13NUlmoogg0KGSaolsG7ZJ%2Fa1%2FRRoxiDKjZcAEq9c%2FvRHjWfE6ogs4QO2HUqxQjpJ7okbRrTbpah3iMRQweUzK0RKF%2BtwxKlYGAXguaieSXKoqipEIv1wc8aiXRLmojNZG8kdmKxUezby5SUyFvap8IesuboSDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/requirements.txt?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NOeCLeBUfWovhkdc4OY4GlFWJ3EnmIOGS4uox7oxQ5pzDRR6e1ary1FBYMQlIk0Qk3oi6T5wx80ajdhKkb4zF6BZHVBa41%2BMkKmEHdi3Xu9bchaVerJRjJO27PyXrXof0LbO6qmmqmiQBBAtaXk%2BUI7PHI5Sekk5E23Org3p42eKNH0ehOxcj9Q13NUlmoogg0KGSaolsG7ZJ%2Fa1%2FRRoxiDKjZcAEq9c%2FvRHjWfE6ogs4QO2HUqxQjpJ7okbRrTbpah3iMRQweUzK0RKF%2BtwxKlYGAXguaieSXKoqipEIv1wc8aiXRLmojNZG8kdmKxUezby5SUyFvap8IesuboSDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C39D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:46,408 ERROR   wandb-upload_4:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:48:46,408 ERROR   wandb-upload_4:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:46,597 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:46,598 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:47,302 ERROR   wandb-upload_5:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-summary.json?Expires=1710420517&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mEUM75XiAZcF6iM9aYZ%2Fy7EuYfp7BlZo%2BcSQ9j1GEEQtlnLHIG7v7CjZfC%2BkH%2FdMiCCqLnGGYatq9xAScz340nV0KS9f6r90qjGgbtTiMsK3Un3lQvM8Xds7KBiFZlf5gF%2Fu0jnlBVp%2FvZ907PkW4r8qrkE2h5DpLi%2F0VWS4Z1c2g5ZQukfB89To9id75Xh0IOgM2BLfmEWIgMab9IQTElzFenkzoSUBaSCEXMTFRmHuYf5DPYsAlKgWk%2FZjwhmEICBX0yM4bLoj%2FbzY5l2nn%2BjaW75aQai7bszs5GSnoxgmqlSCSgOtdMHCwLlmUhWCJpNY5RJXY5MxbMfsWlaHrw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-summary.json?Expires=1710420517&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mEUM75XiAZcF6iM9aYZ%2Fy7EuYfp7BlZo%2BcSQ9j1GEEQtlnLHIG7v7CjZfC%2BkH%2FdMiCCqLnGGYatq9xAScz340nV0KS9f6r90qjGgbtTiMsK3Un3lQvM8Xds7KBiFZlf5gF%2Fu0jnlBVp%2FvZ907PkW4r8qrkE2h5DpLi%2F0VWS4Z1c2g5ZQukfB89To9id75Xh0IOgM2BLfmEWIgMab9IQTElzFenkzoSUBaSCEXMTFRmHuYf5DPYsAlKgWk%2FZjwhmEICBX0yM4bLoj%2FbzY5l2nn%2BjaW75aQai7bszs5GSnoxgmqlSCSgOtdMHCwLlmUhWCJpNY5RJXY5MxbMfsWlaHrw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C1C60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:47,302 ERROR   wandb-upload_5:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 20:48:47,302 ERROR   wandb-upload_5:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:47,612 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:47,613 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:47,613 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:48,625 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:48,625 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:49,631 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:49,632 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:50,633 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:50,633 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:51,644 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:51,644 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:52,655 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:52,655 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:52,656 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:53,665 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:53,666 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:54,681 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:54,682 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:55,696 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:55,696 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:56,711 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:56,712 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:57,717 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:48:57,717 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:57,717 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:58,422 ERROR   wandb-upload_1:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/conda-environment.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sLEV83xl3mwdqsozBHCh22ULXbGNvjggri7N%2BLE2qZMZHGIFPBKFwyfLyWYlLigPAz1eispLKBgzdSiT3uScr2p3jMZWqYcUrtHfsNWX%2FLn0dKXnKOWtw06Wc2%2FuX4%2B79jjIRQJ3c7BhT9wMiaX6BrWDGDWgZbxpwirtuh1i8%2BnrQh5143cS8MLCC5oF62wumPdCIXhjVnn7QLJocPhYewc8LM2OYck%2FOeew6L9Eb56gu5LHKslRg0KKIOIKwKyv0pKiQw9gUJNUN%2BuuDCZ4wLSNgg8fTa%2Bptw26LJNGReempMr29ChCi2LDccqxaLRZJdh%2BhDn%2BSYsWtcOZL0bGBQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/conda-environment.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sLEV83xl3mwdqsozBHCh22ULXbGNvjggri7N%2BLE2qZMZHGIFPBKFwyfLyWYlLigPAz1eispLKBgzdSiT3uScr2p3jMZWqYcUrtHfsNWX%2FLn0dKXnKOWtw06Wc2%2FuX4%2B79jjIRQJ3c7BhT9wMiaX6BrWDGDWgZbxpwirtuh1i8%2BnrQh5143cS8MLCC5oF62wumPdCIXhjVnn7QLJocPhYewc8LM2OYck%2FOeew6L9Eb56gu5LHKslRg0KKIOIKwKyv0pKiQw9gUJNUN%2BuuDCZ4wLSNgg8fTa%2Bptw26LJNGReempMr29ChCi2LDccqxaLRZJdh%2BhDn%2BSYsWtcOZL0bGBQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000272496C33A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:58,422 ERROR   wandb-upload_1:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:48:58,422 ERROR   wandb-upload_1:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:58,718 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:58,718 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:58,731 ERROR   wandb-upload_2:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/config.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZV91a4UbdwfcdaOFCYo6FLPD9HgLKJb17iIQa%2B57VNynILBJ86qZswjYnzKplF7%2FEkQnN4j6P6xdSKkpj%2Fv5ObYrkRdt23Vguz2KszT%2Bau%2BuHRXx6aFmdggDIBrM1g%2FqSZ%2FxbcuHWB8rx9lU51fx7Rs4eBoBmsvsn3FOoyuQ9j%2FAcxziWMUAnT%2BhDSGjcSAmiZxwUZ1VpykBBQ2J6ZXQ6jEKQiUYVTqr7W3Yp0Amvz0ih8BwLKdriDSiCBtWaUf2LUq9bp987uGCzFaWBZH2VOUvSOp8kO%2BmvpRxg3WUnHjaw0mTQekwMkbPI4%2BRoCqcmdC67vrJGWzyRLXv%2FzMVWA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/config.yaml?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZV91a4UbdwfcdaOFCYo6FLPD9HgLKJb17iIQa%2B57VNynILBJ86qZswjYnzKplF7%2FEkQnN4j6P6xdSKkpj%2Fv5ObYrkRdt23Vguz2KszT%2Bau%2BuHRXx6aFmdggDIBrM1g%2FqSZ%2FxbcuHWB8rx9lU51fx7Rs4eBoBmsvsn3FOoyuQ9j%2FAcxziWMUAnT%2BhDSGjcSAmiZxwUZ1VpykBBQ2J6ZXQ6jEKQiUYVTqr7W3Yp0Amvz0ih8BwLKdriDSiCBtWaUf2LUq9bp987uGCzFaWBZH2VOUvSOp8kO%2BmvpRxg3WUnHjaw0mTQekwMkbPI4%2BRoCqcmdC67vrJGWzyRLXv%2FzMVWA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027249619CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:58,731 ERROR   wandb-upload_2:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '455'}
2024-03-13 20:48:58,731 ERROR   wandb-upload_2:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:59,049 ERROR   wandb-upload_3:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/output.log?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QvDbmTRMgBIrJfJDnPI0SJ2kCCIv8zovp1jVvKxIYiiqhDwYG%2BuwUn9CcXbICchIDiA0PmprBvWc9ODqhqaoI5fgPrMoSqwANEypfy%2B72uEKjeQ1Z%2FjRsYw%2Fpn9aYNahx1cVlXv%2B2JOAjvXgLT5QuekJLa%2FVP%2FPcy4iFKgyPf0Y5NFh3E7Z%2F3kgO9AxMsl%2FjsN2HQFGeYdjNmGWHVbcAtNHGOXn0r2T5ZszHmgAGR4WJLnWI1L6vzAW%2BQelTeaFtJyna7gQND%2FVstKGu31z9BPrPXWs4r2mnMttw2IjdKbn8Lka7H%2BYEcMPRszzQU30AIxcLVoc%2Fl1bevi75Pzu%2Btg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/output.log?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QvDbmTRMgBIrJfJDnPI0SJ2kCCIv8zovp1jVvKxIYiiqhDwYG%2BuwUn9CcXbICchIDiA0PmprBvWc9ODqhqaoI5fgPrMoSqwANEypfy%2B72uEKjeQ1Z%2FjRsYw%2Fpn9aYNahx1cVlXv%2B2JOAjvXgLT5QuekJLa%2FVP%2FPcy4iFKgyPf0Y5NFh3E7Z%2F3kgO9AxMsl%2FjsN2HQFGeYdjNmGWHVbcAtNHGOXn0r2T5ZszHmgAGR4WJLnWI1L6vzAW%2BQelTeaFtJyna7gQND%2FVstKGu31z9BPrPXWs4r2mnMttw2IjdKbn8Lka7H%2BYEcMPRszzQU30AIxcLVoc%2Fl1bevi75Pzu%2Btg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027249619840>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:59,049 ERROR   wandb-upload_3:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1442'}
2024-03-13 20:48:59,049 ERROR   wandb-upload_3:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:48:59,733 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:48:59,734 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:48:59,922 ERROR   wandb-upload_4:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/requirements.txt?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NOeCLeBUfWovhkdc4OY4GlFWJ3EnmIOGS4uox7oxQ5pzDRR6e1ary1FBYMQlIk0Qk3oi6T5wx80ajdhKkb4zF6BZHVBa41%2BMkKmEHdi3Xu9bchaVerJRjJO27PyXrXof0LbO6qmmqmiQBBAtaXk%2BUI7PHI5Sekk5E23Org3p42eKNH0ehOxcj9Q13NUlmoogg0KGSaolsG7ZJ%2Fa1%2FRRoxiDKjZcAEq9c%2FvRHjWfE6ogs4QO2HUqxQjpJ7okbRrTbpah3iMRQweUzK0RKF%2BtwxKlYGAXguaieSXKoqipEIv1wc8aiXRLmojNZG8kdmKxUezby5SUyFvap8IesuboSDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/requirements.txt?Expires=1710420515&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NOeCLeBUfWovhkdc4OY4GlFWJ3EnmIOGS4uox7oxQ5pzDRR6e1ary1FBYMQlIk0Qk3oi6T5wx80ajdhKkb4zF6BZHVBa41%2BMkKmEHdi3Xu9bchaVerJRjJO27PyXrXof0LbO6qmmqmiQBBAtaXk%2BUI7PHI5Sekk5E23Org3p42eKNH0ehOxcj9Q13NUlmoogg0KGSaolsG7ZJ%2Fa1%2FRRoxiDKjZcAEq9c%2FvRHjWfE6ogs4QO2HUqxQjpJ7okbRrTbpah3iMRQweUzK0RKF%2BtwxKlYGAXguaieSXKoqipEIv1wc8aiXRLmojNZG8kdmKxUezby5SUyFvap8IesuboSDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027246EC8DF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:48:59,922 ERROR   wandb-upload_4:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:48:59,922 ERROR   wandb-upload_4:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:49:00,750 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:00,750 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:00,874 ERROR   wandb-upload_5:28992 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-summary.json?Expires=1710420517&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mEUM75XiAZcF6iM9aYZ%2Fy7EuYfp7BlZo%2BcSQ9j1GEEQtlnLHIG7v7CjZfC%2BkH%2FdMiCCqLnGGYatq9xAScz340nV0KS9f6r90qjGgbtTiMsK3Un3lQvM8Xds7KBiFZlf5gF%2Fu0jnlBVp%2FvZ907PkW4r8qrkE2h5DpLi%2F0VWS4Z1c2g5ZQukfB89To9id75Xh0IOgM2BLfmEWIgMab9IQTElzFenkzoSUBaSCEXMTFRmHuYf5DPYsAlKgWk%2FZjwhmEICBX0yM4bLoj%2FbzY5l2nn%2BjaW75aQai7bszs5GSnoxgmqlSCSgOtdMHCwLlmUhWCJpNY5RJXY5MxbMfsWlaHrw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/cdqyb3ac/wandb-summary.json?Expires=1710420517&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mEUM75XiAZcF6iM9aYZ%2Fy7EuYfp7BlZo%2BcSQ9j1GEEQtlnLHIG7v7CjZfC%2BkH%2FdMiCCqLnGGYatq9xAScz340nV0KS9f6r90qjGgbtTiMsK3Un3lQvM8Xds7KBiFZlf5gF%2Fu0jnlBVp%2FvZ907PkW4r8qrkE2h5DpLi%2F0VWS4Z1c2g5ZQukfB89To9id75Xh0IOgM2BLfmEWIgMab9IQTElzFenkzoSUBaSCEXMTFRmHuYf5DPYsAlKgWk%2FZjwhmEICBX0yM4bLoj%2FbzY5l2nn%2BjaW75aQai7bszs5GSnoxgmqlSCSgOtdMHCwLlmUhWCJpNY5RJXY5MxbMfsWlaHrw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027246EC9150>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:49:00,875 ERROR   wandb-upload_5:28992 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '209'}
2024-03-13 20:49:00,875 ERROR   wandb-upload_5:28992 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:49:01,764 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:01,764 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:02,767 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:49:02,768 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:02,768 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:03,770 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:03,771 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:04,783 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:04,784 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:05,797 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:05,798 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:06,461 INFO    wandb-upload_0:28992 [upload_job.py:push():131] Uploaded file C:\Users\lenovo\AppData\Local\Temp\tmpcf4jq3vawandb\pev1kl7d-wandb-metadata.json
2024-03-13 20:49:06,801 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:06,802 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:07,812 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:07,812 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:49:07,813 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:08,817 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:08,817 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:09,829 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:09,829 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:10,830 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:10,830 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:49:11,833 DEBUG   HandlerThread:28992 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:49:11,834 DEBUG   SenderThread:28992 [sender.py:send_request():407] send_request: poll_exit
