2024-03-13 20:24:31,396 INFO    StreamThr :1768 [internal.py:wandb_internal():86] W&B internal server running at pid: 1768, started at: 2024-03-13 20:24:31.395702
2024-03-13 20:24:31,397 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status
2024-03-13 20:24:31,403 INFO    WriterThread:1768 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\run-3f7g31f7.wandb
2024-03-13 20:24:31,405 DEBUG   SenderThread:1768 [sender.py:send():380] send: header
2024-03-13 20:24:31,405 DEBUG   SenderThread:1768 [sender.py:send():380] send: run
2024-03-13 20:24:32,383 INFO    SenderThread:1768 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files
2024-03-13 20:24:32,383 INFO    SenderThread:1768 [sender.py:_start_run_threads():1122] run started: 3f7g31f7 with start time 1710332671.397703
2024-03-13 20:24:32,402 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 20:24:32,403 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: check_version
2024-03-13 20:24:35,598 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 20:24:35,640 DEBUG   HandlerThread:1768 [system_info.py:__init__():32] System info init
2024-03-13 20:24:35,640 DEBUG   HandlerThread:1768 [system_info.py:__init__():47] System info init done
2024-03-13 20:24:35,640 INFO    HandlerThread:1768 [system_monitor.py:start():181] Starting system monitor
2024-03-13 20:24:35,640 INFO    SystemMonitor:1768 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 20:24:35,641 INFO    HandlerThread:1768 [system_monitor.py:probe():201] Collecting system info
2024-03-13 20:24:35,645 INFO    SystemMonitor:1768 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 20:24:35,646 INFO    SystemMonitor:1768 [interfaces.py:start():190] Started disk monitoring
2024-03-13 20:24:35,647 INFO    SystemMonitor:1768 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 20:24:35,647 INFO    SystemMonitor:1768 [interfaces.py:start():190] Started memory monitoring
2024-03-13 20:24:35,662 INFO    SystemMonitor:1768 [interfaces.py:start():190] Started network monitoring
2024-03-13 20:24:35,685 DEBUG   HandlerThread:1768 [system_info.py:probe():196] Probing system
2024-03-13 20:24:35,685 DEBUG   HandlerThread:1768 [system_info.py:probe():244] Probing system done
2024-03-13 20:24:35,685 DEBUG   HandlerThread:1768 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T12:24:35.685784', 'startedAt': '2024-03-13T12:24:31.375697', 'docker': None, 'cuda': None, 'args': ('--task=W', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 243.48526000976562}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 20:24:35,685 INFO    HandlerThread:1768 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 20:24:35,685 INFO    HandlerThread:1768 [system_monitor.py:probe():214] Publishing system info
2024-03-13 20:24:35,685 DEBUG   HandlerThread:1768 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 20:24:35,686 DEBUG   HandlerThread:1768 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 20:24:35,687 DEBUG   HandlerThread:1768 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 20:24:35,696 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:36,414 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\requirements.txt
2024-03-13 20:24:36,414 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\conda-environment.yaml
2024-03-13 20:24:37,749 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:39,782 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:41,830 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:43,341 DEBUG   HandlerThread:1768 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 20:24:43,342 INFO    HandlerThread:1768 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 20:24:43,365 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:24:43,365 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:24:43,365 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:24:43,366 DEBUG   SenderThread:1768 [sender.py:send():380] send: files
2024-03-13 20:24:43,366 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 20:24:43,378 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:24:43,379 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:24:43,379 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:24:43,454 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\conda-environment.yaml
2024-03-13 20:24:43,454 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-metadata.json
2024-03-13 20:24:43,858 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:44,176 DEBUG   SenderThread:1768 [sender.py:send():380] send: telemetry
2024-03-13 20:24:44,456 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:24:45,896 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:46,483 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:24:47,197 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:24:47,932 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:49,971 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:51,233 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F211F90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:24:51,234 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:24:51,234 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:24:52,004 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:52,220 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:24:53,268 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:24:53,269 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:24:53,269 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:24:53,275 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:24:53,550 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:24:54,046 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:54,565 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:24:56,079 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:56,125 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:24:56,126 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:24:56,127 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:24:56,127 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:24:56,128 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:24:56,129 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:24:56,129 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:24:56,130 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:24:56,571 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:24:58,119 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:24:58,145 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:24:58,386 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:24:58,386 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:24:58,386 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:24:58,577 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:24:59,628 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F212980>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:24:59,628 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:24:59,628 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:25:00,162 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:00,597 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:00,597 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:00,598 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:00,599 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:01,595 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:02,201 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:02,535 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:02,536 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:02,537 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:02,537 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:02,538 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:02,539 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:02,539 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:02,540 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:02,600 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:02,601 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:03,558 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:04,243 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:04,609 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\config.yaml
2024-03-13 20:25:04,610 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:06,355 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:07,123 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:07,124 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:07,124 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:07,126 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:07,638 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:08,396 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:08,641 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:09,097 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F450250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:25:09,097 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:25:09,097 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:25:09,097 INFO    wandb-upload_0:1768 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001AE2F450250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F450250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F450250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 20:25:09,132 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:09,290 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:09,291 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:09,291 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:09,292 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:09,293 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:09,294 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:09,294 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:09,295 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:09,643 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:10,425 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:10,648 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:12,455 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:13,391 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:25:13,391 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:25:13,392 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:25:13,861 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:14,272 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:14,272 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:14,272 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:14,273 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:14,484 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:14,683 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:15,816 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:15,816 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:15,817 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:15,817 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:15,819 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:15,819 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:15,819 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:15,820 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:16,514 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:16,687 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:16,688 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:18,548 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:19,836 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:20,293 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:20,294 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:20,294 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:20,295 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:20,580 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:20,713 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:20,714 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:21,475 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F451810>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:25:21,476 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:25:21,476 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:25:22,319 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:22,320 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:22,320 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:22,321 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:22,322 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:22,322 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:22,322 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:22,323 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:22,615 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:22,721 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:22,721 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:24,644 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:25,340 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:26,679 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:26,833 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:26,834 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:26,834 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:26,835 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:27,746 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:28,383 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:25:28,383 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:25:28,383 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:25:28,717 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:28,749 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:28,840 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:28,840 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:28,841 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:28,842 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:28,843 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:28,844 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:28,844 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:28,845 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:29,756 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:30,761 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:30,764 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:30,855 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:32,802 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:33,274 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:33,275 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:33,275 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:33,276 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:33,792 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:34,830 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:34,847 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:35,246 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:35,247 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:35,247 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:35,248 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:35,249 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:35,249 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:35,249 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:35,250 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:35,677 DEBUG   SystemMonitor:1768 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 20:25:35,678 DEBUG   SenderThread:1768 [sender.py:send():380] send: stats
2024-03-13 20:25:35,837 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:36,693 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:36,883 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:36,950 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:38,278 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F212980>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:25:38,279 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:25:38,279 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:25:38,983 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:39,723 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:39,724 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:39,724 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:39,726 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:39,932 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:40,947 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:41,015 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:41,710 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:41,710 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:41,711 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:41,712 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:41,713 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:41,714 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:41,714 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:41,714 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:41,715 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:41,958 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:42,988 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:43,039 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:43,384 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:25:43,385 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:25:43,400 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:25:45,074 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:46,252 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:46,253 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:46,253 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:46,254 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:47,053 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:47,053 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:47,106 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:47,262 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:48,282 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:48,282 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:48,284 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:48,284 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:48,285 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:48,285 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:48,286 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:48,286 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:49,093 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:49,093 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:49,129 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:51,162 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:52,318 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:52,866 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:52,867 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:52,867 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:52,869 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:53,185 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:53,206 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:54,913 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:54,914 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:54,914 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:54,915 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:54,916 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:54,916 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:54,916 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:54,917 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:25:55,218 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:55,219 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:25:55,236 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:57,257 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:25:57,275 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:57,927 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:25:58,390 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:25:58,390 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:25:58,406 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:25:59,315 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:25:59,387 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:25:59,388 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:25:59,388 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:25:59,389 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:00,305 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:01,334 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:01,356 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:01,382 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:01,382 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:01,383 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:01,384 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:01,385 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:01,385 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:01,385 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:01,386 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:02,339 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:03,108 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F432CB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:26:03,109 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:26:03,109 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:26:03,368 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:03,390 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:03,398 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:05,424 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:05,691 DEBUG   SenderThread:1768 [sender.py:send():380] send: stats
2024-03-13 20:26:05,887 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:05,888 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:05,888 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:05,889 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:06,420 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:07,447 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:07,511 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:07,846 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:07,846 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:07,847 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:07,847 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:07,848 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:07,849 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:07,849 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:07,850 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:08,460 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:08,858 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:09,478 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:09,530 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:11,557 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:12,334 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:12,335 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:12,335 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:12,336 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:12,526 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:13,386 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:26:13,387 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:26:13,418 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:26:13,580 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:14,382 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:14,382 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:14,383 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:14,384 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:14,384 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:14,385 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:14,385 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:14,386 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:14,386 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:14,566 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:15,600 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:15,629 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:17,642 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:17,662 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:18,875 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:18,876 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:18,876 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:18,877 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:19,681 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:19,699 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:19,888 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:20,683 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:20,964 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:20,964 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:20,965 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:20,965 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:20,966 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:20,967 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:20,967 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:20,968 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:21,717 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:21,736 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:22,726 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:23,778 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:24,991 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:25,421 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:25,422 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:25,422 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:25,423 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:25,802 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:25,822 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:26,811 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:27,382 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:27,383 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:27,384 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:27,384 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:27,385 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:27,386 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:27,386 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:27,386 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:27,849 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:27,860 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:28,389 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:26:28,389 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:26:28,420 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:26:28,852 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:29,906 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:30,252 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:31,860 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:31,861 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:31,861 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:31,862 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:31,923 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:31,942 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:32,938 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:33,855 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:33,856 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:33,857 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:33,857 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:33,858 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:33,859 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:33,859 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:33,860 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:33,966 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:33,984 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:34,971 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:35,704 DEBUG   SenderThread:1768 [sender.py:send():380] send: stats
2024-03-13 20:26:35,705 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:36,026 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:38,110 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:38,625 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:38,626 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:38,626 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:38,627 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:39,051 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:40,133 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:40,651 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:40,652 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:40,653 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:40,653 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:40,654 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:40,654 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:40,655 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:40,655 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:41,083 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:41,084 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:41,672 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:42,153 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:43,124 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:43,379 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:26:43,380 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:26:43,426 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:26:44,178 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:45,087 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:45,088 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:45,088 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:45,089 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:45,165 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:46,218 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:47,080 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:47,080 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:47,081 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:47,081 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:47,082 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:47,083 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:47,083 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:47,083 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:47,084 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:47,206 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:47,207 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:48,257 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:48,950 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4514E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:26:48,950 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:26:48,950 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:26:49,239 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:50,292 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:51,502 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:51,503 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:51,503 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:51,504 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:52,316 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:52,341 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:52,507 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:53,321 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:53,452 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:53,453 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:53,453 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:53,454 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:53,455 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:53,455 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:53,455 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:53,456 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:54,347 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:54,372 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:55,352 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:56,401 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:57,958 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:26:57,958 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:57,959 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:57,959 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:57,960 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:58,412 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:26:58,413 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:26:58,414 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:26:58,430 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:26:58,433 ERROR   gpu       :1768 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:26:59,416 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:26:59,958 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:59,958 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:26:59,959 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:59,960 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:59,960 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:26:59,961 DEBUG   SenderThread:1768 [sender.py:send():380] send: history
2024-03-13 20:26:59,961 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:26:59,962 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:27:00,126 DEBUG   SenderThread:1768 [sender.py:send():380] send: exit
2024-03-13 20:27:00,126 INFO    SenderThread:1768 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 20:27:00,127 INFO    SenderThread:1768 [sender.py:send_exit():587] handling runtime: 144
2024-03-13 20:27:00,127 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:27:00,128 INFO    SenderThread:1768 [sender.py:send_exit():593] send defer
2024-03-13 20:27:00,128 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,128 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 20:27:00,128 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,128 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 20:27:00,128 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 1
2024-03-13 20:27:00,129 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,129 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 20:27:00,129 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,129 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 20:27:00,129 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 2
2024-03-13 20:27:00,129 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,129 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 20:27:00,129 INFO    HandlerThread:1768 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 20:27:00,129 DEBUG   SystemMonitor:1768 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 20:27:00,137 DEBUG   SystemMonitor:1768 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 20:27:00,138 INFO    HandlerThread:1768 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 20:27:00,138 INFO    HandlerThread:1768 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 20:27:00,184 INFO    HandlerThread:1768 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 20:27:00,184 INFO    HandlerThread:1768 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 20:27:00,184 INFO    HandlerThread:1768 [interfaces.py:finish():202] Joined network monitor
2024-03-13 20:27:00,185 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,185 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 20:27:00,185 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 3
2024-03-13 20:27:00,185 DEBUG   SenderThread:1768 [sender.py:send():380] send: stats
2024-03-13 20:27:00,185 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,186 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 20:27:00,186 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,186 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 20:27:00,186 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 4
2024-03-13 20:27:00,186 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,186 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 20:27:00,186 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,186 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 20:27:00,187 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 5
2024-03-13 20:27:00,187 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,187 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 20:27:00,187 DEBUG   SenderThread:1768 [sender.py:send():380] send: summary
2024-03-13 20:27:00,188 INFO    SenderThread:1768 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:27:00,188 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,188 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 20:27:00,189 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 6
2024-03-13 20:27:00,189 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,189 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 20:27:00,189 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,189 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 20:27:00,189 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 7
2024-03-13 20:27:00,190 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:00,190 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,190 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 20:27:00,190 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,190 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 20:27:00,427 INFO    Thread-12 :1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json
2024-03-13 20:27:00,816 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 8
2024-03-13 20:27:00,817 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,817 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 20:27:00,817 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,817 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 20:27:00,817 INFO    SenderThread:1768 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 20:27:00,818 INFO    SenderThread:1768 [job_builder.py:_get_source_type():404] no source found
2024-03-13 20:27:00,818 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 9
2024-03-13 20:27:00,818 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:00,818 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 20:27:00,818 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:00,819 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 20:27:00,819 INFO    SenderThread:1768 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 20:27:01,129 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:01,438 INFO    SenderThread:1768 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log
2024-03-13 20:27:01,440 INFO    SenderThread:1768 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files
2024-03-13 20:27:01,440 INFO    SenderThread:1768 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\conda-environment.yaml conda-environment.yaml
2024-03-13 20:27:01,441 INFO    SenderThread:1768 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\config.yaml config.yaml
2024-03-13 20:27:01,443 INFO    SenderThread:1768 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\output.log output.log
2024-03-13 20:27:01,445 INFO    SenderThread:1768 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\requirements.txt requirements.txt
2024-03-13 20:27:01,447 INFO    SenderThread:1768 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-metadata.json wandb-metadata.json
2024-03-13 20:27:01,447 INFO    SenderThread:1768 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_202431-3f7g31f7\files\wandb-summary.json wandb-summary.json
2024-03-13 20:27:01,449 INFO    SenderThread:1768 [sender.py:transition_state():613] send defer: 10
2024-03-13 20:27:01,450 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:01,450 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:27:01,450 INFO    HandlerThread:1768 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 20:27:01,452 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: defer
2024-03-13 20:27:01,452 INFO    SenderThread:1768 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 20:27:01,452 INFO    SenderThread:1768 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 20:27:02,143 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:02,143 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:03,143 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:03,144 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:04,156 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:04,156 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:05,169 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:05,169 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:06,182 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:06,183 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:07,184 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:07,184 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:08,197 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:08,197 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:08,198 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:09,212 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:09,212 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:09,268 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4539D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:09,269 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:27:09,269 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:09,451 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F433700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:09,451 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:27:09,451 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:09,586 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F433640>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:09,586 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '212'}
2024-03-13 20:27:09,586 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:09,681 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F433A60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:09,681 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1463'}
2024-03-13 20:27:09,682 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:10,212 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:10,213 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:11,213 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:11,214 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:12,226 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:12,226 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:12,993 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F451BD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:12,993 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:27:12,993 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:13,239 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:13,239 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:13,240 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:14,254 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:14,255 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:15,254 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:15,254 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:16,270 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:16,270 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:17,278 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:17,278 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:17,829 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F450C40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:17,829 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:27:17,829 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:18,131 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F451090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:18,131 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F452590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:18,131 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4503D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:18,131 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:27:18,131 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1463'}
2024-03-13 20:27:18,131 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '212'}
2024-03-13 20:27:18,132 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:18,132 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:18,132 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:18,288 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:18,288 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:18,289 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:19,290 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:19,291 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:20,305 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:20,305 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:21,316 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:21,316 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:21,469 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F453D60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:21,470 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:27:21,470 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:22,326 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:22,326 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:23,330 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:23,330 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:23,331 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:24,344 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:24,344 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:25,356 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:25,356 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:26,366 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:26,366 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:27,369 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:27,369 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:27,633 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2CAFCF40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:27,633 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:27:27,634 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:27,699 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4505B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:27,700 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F453550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:27,700 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:27:27,700 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1463'}
2024-03-13 20:27:27,700 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:27,700 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:28,144 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4533A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:28,144 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '212'}
2024-03-13 20:27:28,144 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:28,381 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:28,381 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:28,382 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:29,382 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:29,382 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:30,387 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:30,387 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:30,748 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F453400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:30,748 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:27:30,748 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:31,400 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:31,400 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:32,404 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:32,404 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:33,405 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:33,405 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:33,406 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:34,412 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:34,412 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:35,417 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:35,417 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:36,423 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:36,424 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:37,435 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:37,436 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:38,441 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:38,441 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:38,441 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:38,956 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F1D47C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:38,956 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1463'}
2024-03-13 20:27:38,956 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:39,450 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:39,450 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:39,554 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F2111B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:39,554 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:27:39,554 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:39,910 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4339D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:39,910 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '212'}
2024-03-13 20:27:39,910 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:40,230 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F433640>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:40,230 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:27:40,230 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:40,458 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:40,458 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:41,471 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:41,471 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:42,485 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:42,485 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:42,988 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2CAFCB80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:42,988 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:27:42,989 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:43,496 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:43,497 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:43,497 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:44,499 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:44,500 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:45,502 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:45,502 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:46,509 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:46,509 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:47,516 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:47,517 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:48,527 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:48,528 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:48,528 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:49,541 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:49,541 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:50,555 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:50,555 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:51,566 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:51,567 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:52,569 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:52,570 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:53,578 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:53,578 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:53,579 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:54,586 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:54,586 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:54,876 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F2113C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:54,876 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:27:54,876 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:55,597 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:55,597 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:55,675 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F453610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:55,675 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1463'}
2024-03-13 20:27:55,675 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:56,076 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F212AA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:56,076 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:27:56,076 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:56,605 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:56,605 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:56,668 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F453B50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:56,669 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '212'}
2024-03-13 20:27:56,669 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:27:57,607 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:57,607 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:58,620 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:58,621 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:27:58,621 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:59,622 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:27:59,622 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:27:59,916 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F4500D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:27:59,916 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:27:59,916 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:00,624 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:00,624 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:01,629 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:01,630 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:02,638 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:02,638 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:03,641 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:03,641 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:03,641 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:04,644 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:04,644 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:05,647 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:05,648 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:06,652 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:06,653 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:07,654 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:07,655 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:08,353 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-metadata.json?Expires=1710419086&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XB6ArTaeelJSCXxVwnRX53eVml5WqKloGV6pBFYtt3DLJTuwaxb8%2BMGAbmDIRFLPJIWQBe9KwFRiQOlRBvSZdOJBx5mX5xB3anQ2yGmfMKbvFal2XjPR%2FrR7Bqw6lS6Ugz0pVCXjdd2DCR0800WFJhWfrYQN91dAyOacjeEokfY2MuCJser72o1Q2AHaj9cjNEasLSSAbiqKQz4KV3dwbV56pMUZc78efBiWG%2B5wbkG2%2FUSTinM%2BvLdCCQVfuyfd2LhQ8%2FaeBckKc4fr90y67rkb937F6%2FaNYgIuKdavT1vpZXE0GJ4GIxcoO18djLntOrgNkBNDRJ6tEI02jaP81A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F450520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:28:08,353 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:28:08,353 ERROR   wandb-upload_0:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:08,665 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:08,666 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:08,666 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:09,668 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:09,669 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:10,675 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:10,675 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:11,689 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:11,689 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:12,702 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:12,703 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:13,702 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:13,704 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:13,704 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:14,717 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:14,718 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:15,729 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:15,729 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:16,740 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:16,740 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:17,750 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:17,751 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:18,760 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:18,761 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:18,761 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:19,773 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:19,774 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:19,836 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/conda-environment.yaml?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Yq%2FZCXrr4hcS0zP117y2vrwS2IL%2F3aTIw006SHaQRH9RpBKkKMLkO5nH88S1gfwcJE2cjsXzJ3czGN0CRUSy017ifFyvMQD6N327pNvLJEQIAwfaD7KV3nYduyxdqE32sGaxYhmrxvq%2FgCwi2GVn2PHyG4sLyu%2F69%2Fi5TZgGGQJxol%2BY9dXAPiSZjhnGtfyGA6ipc7CTPTnl1AjptbKquaTeTQTzJDVdjbXXpdxk7dBRCAJp6VyD7aGjyaoE413JzqAtwBsNUaZtaN2p87YCx9vxyE58PPN09k7fxE8Mpu0QmpTnVRkVGW2PcOSPeusyNHO%2FlJrNXeBCXU99H2SgDA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F450C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:28:19,836 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:28:19,836 ERROR   wandb-upload_1:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:20,787 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:20,788 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:21,169 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/wandb-summary.json?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=mKmgNVsrgcTFkaKh%2BC5Yw39EWVBsJem0lfxsZvp1K8O0EbvySAO2QUWeCTcfWQgjWHtQJPKm%2FJvrxsv6PJk89ASM6xRFMECIXmZYbcfs8FDW%2BI4JCeySQhIKnRkXXnQ3lxRN%2BFiIt799t2CmERwZv9zNNdPgI79TXwuNKOfVOVYtjG1rd4G%2FPjCLx1VWR5J3BBQ%2Fr4BXRAgs%2B1VeD9IyDDM4vlBERq8dxj5UATnReciGukJimEAaPOPNIsO4KcwxPKFiGKDHrararYfdBvFXEK7Qp%2B1hYj7Z2pXHZn2kBG0pon2LgjUV3v1JynlQLOeEve%2BO9zAIsiAm4m2xAzwpag%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F452EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:28:21,170 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '212'}
2024-03-13 20:28:21,170 ERROR   wandb-upload_5:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:21,802 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:21,803 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:22,108 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/output.log?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZtoieMCFBUjHHaoJaWbXDJhwkFEnRXn6wOOBREh38NahufTxYad5GikgvouMj%2FFR8kz4au6W6YWIxOlVgTiy1h1xLs9JSK6ac%2BTwEGKDNppBdRd1KaNgk8ylf%2Fo%2FQHVw0CKw%2FD8STS9InhpTQd%2BiAfmV8SmOleRSvT8XIs%2Fva54Hm9fyOGPPlJYcg8U6z2uEHvpc7gCXOk2rC3UVIWyDqHySVkQtqmdu12lWb%2FKVnfxl8dWhTVwEHlXVv%2B93sbOqhpHWYvLataAscrU482cpcM%2BKRuJQ6te6a5d5EgEQsH8JwEETrqHIBi%2BlB8qRQrQTJ81kUwmoqGR30x7IwK85pA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2CAFC880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:28:22,108 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/requirements.txt?Expires=1710419224&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=RP1RbxFCfn%2B1pQmVZa8lipD4pBHaHlqPAvaF1DWNlONUH5cRM8W4A8oqTm53Yu2ddXHVZu60JVwWd36mNEh39UyrjznHaCQndK3K0v60wwrP26p8HRJZZs1zV%2FieVBbgxpHh%2F6oEdk%2F9F5MI2h104hmbPFQ8IpZ31Vqh6VshcmqIHUSKdO7i59YFdo21qmiikQ4tS8JKl1kVEzuddrSDnJpfP4MNfSnHK6RHLJBCN8%2BlJZiEnayElGtw5OJgGg8qf0ne41QCX4MIyaBo1HWgKeCxD5%2Fnh7oSYFumlqFuSLwhEkD6b1M0%2BrupR5Th5ucMhJVV3jp8LWRXHhTH1%2FHLrg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F452F20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:28:22,108 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1463'}
2024-03-13 20:28:22,108 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:28:22,109 ERROR   wandb-upload_3:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:22,109 ERROR   wandb-upload_4:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:22,807 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:22,808 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:23,809 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:23,809 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:23,810 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:24,814 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:24,815 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:25,792 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/3f7g31f7/config.yaml?Expires=1710419227&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dqJ6gV%2Fdy%2Fk5D%2BjzvEYhG3cPYXlJSN6%2FRziOcqGXDwfTdc8F1hqaLXLtEz3Z%2BFCA74%2BRamyYv1Fu9vY171MXTJ41FR7fvHUX9dhY8%2F6WNfz0n%2B5H%2BKHY69rBo%2FbRUn4qfuUp2wxDiBLHN3Q%2B0EyOmCT1iejyepZgJ9wBGQsFIfbfwY6BH%2BDjzxZbJzfQDnnTiIRBCJgkl%2B7W8Ql%2BwYkjZGbRs5AE2sQVgBVYCFhTIM4vAEjZYmaCozh6%2BBU%2Fxf6Rub44LFtix18ohiDBbD%2FtNANDzey%2BtXtMS4%2F6WBkIISaI6ygs%2FsR7vAaY3%2BkCTPsuAEwvp8nFXbzEW5KiRdJOGA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AE2F453400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:28:25,792 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:28:25,792 ERROR   wandb-upload_2:1768 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:28:25,824 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:25,825 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:26,826 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:26,826 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:27,842 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:27,842 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:28,845 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:28,846 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:28,846 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:29,846 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:29,846 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:30,853 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:30,854 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:31,857 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:31,858 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:32,861 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:32,861 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:33,875 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:33,875 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:33,876 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:34,889 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:34,890 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:35,904 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:35,905 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:36,909 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:36,909 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:37,910 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:37,910 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:38,918 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:38,919 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:38,919 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:39,930 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:39,931 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:40,942 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:40,942 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:41,944 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:41,945 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:42,947 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:42,947 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:43,953 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:43,954 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:43,954 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:44,968 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:44,969 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:45,982 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:45,983 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:46,983 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:46,983 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:47,985 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:47,986 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:48,990 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:48,990 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:48,990 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:50,003 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:50,003 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:51,007 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:51,007 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:52,014 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:52,014 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:53,023 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:53,024 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:54,028 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:54,028 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:28:54,029 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:55,037 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:55,037 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:56,044 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:56,044 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:28:57,056 DEBUG   HandlerThread:1768 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:28:57,057 DEBUG   SenderThread:1768 [sender.py:send_request():407] send_request: poll_exit
