2023-11-26 14:37:29,690 INFO    StreamThr :21580 [internal.py:wandb_internal():86] W&B internal server running at pid: 21580, started at: 2023-11-26 14:37:29.690084
2023-11-26 14:37:29,691 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status
2023-11-26 14:37:29,695 INFO    WriterThread:21580 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\run-imwjep7k.wandb
2023-11-26 14:37:29,697 DEBUG   SenderThread:21580 [sender.py:send():380] send: header
2023-11-26 14:37:29,697 DEBUG   SenderThread:21580 [sender.py:send():380] send: run
2023-11-26 14:37:30,547 INFO    SenderThread:21580 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files
2023-11-26 14:37:30,560 INFO    SenderThread:21580 [sender.py:_start_run_threads():1122] run started: imwjep7k with start time 1700980649.69061
2023-11-26 14:37:30,568 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: check_version
2023-11-26 14:37:30,568 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: check_version
2023-11-26 14:37:35,570 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:35,583 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: run_start
2023-11-26 14:37:35,646 DEBUG   HandlerThread:21580 [system_info.py:__init__():32] System info init
2023-11-26 14:37:35,646 DEBUG   HandlerThread:21580 [system_info.py:__init__():47] System info init done
2023-11-26 14:37:35,646 INFO    HandlerThread:21580 [system_monitor.py:start():181] Starting system monitor
2023-11-26 14:37:35,646 INFO    SystemMonitor:21580 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-11-26 14:37:35,647 INFO    HandlerThread:21580 [system_monitor.py:probe():201] Collecting system info
2023-11-26 14:37:35,651 INFO    SystemMonitor:21580 [interfaces.py:start():190] Started cpu monitoring
2023-11-26 14:37:35,651 INFO    SystemMonitor:21580 [interfaces.py:start():190] Started disk monitoring
2023-11-26 14:37:35,652 INFO    SystemMonitor:21580 [interfaces.py:start():190] Started gpu monitoring
2023-11-26 14:37:35,653 INFO    SystemMonitor:21580 [interfaces.py:start():190] Started memory monitoring
2023-11-26 14:37:35,674 INFO    SystemMonitor:21580 [interfaces.py:start():190] Started network monitoring
2023-11-26 14:37:35,706 DEBUG   HandlerThread:21580 [system_info.py:probe():196] Probing system
2023-11-26 14:37:35,707 DEBUG   HandlerThread:21580 [system_info.py:probe():244] Probing system done
2023-11-26 14:37:35,707 DEBUG   HandlerThread:21580 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2023-11-26T06:37:35.706734', 'startedAt': '2023-11-26T06:37:29.666995', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2555.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 2555.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 103.92399215698242}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2023-11-26 14:37:35,707 INFO    HandlerThread:21580 [system_monitor.py:probe():211] Finished collecting system info
2023-11-26 14:37:35,707 INFO    HandlerThread:21580 [system_monitor.py:probe():214] Publishing system info
2023-11-26 14:37:35,707 DEBUG   HandlerThread:21580 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-11-26 14:37:35,708 DEBUG   HandlerThread:21580 [system_info.py:_save_pip():68] Saving pip packages done
2023-11-26 14:37:35,708 DEBUG   HandlerThread:21580 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-11-26 14:37:35,712 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:36,603 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\conda-environment.yaml
2023-11-26 14:37:36,603 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\requirements.txt
2023-11-26 14:37:37,772 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:39,815 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:41,637 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\conda-environment.yaml
2023-11-26 14:37:41,773 DEBUG   HandlerThread:21580 [system_info.py:_save_conda():87] Saving conda packages done
2023-11-26 14:37:41,774 INFO    HandlerThread:21580 [system_monitor.py:probe():216] Finished publishing system info
2023-11-26 14:37:41,789 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:41,789 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:41,789 DEBUG   SenderThread:21580 [sender.py:send():380] send: files
2023-11-26 14:37:41,789 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-11-26 14:37:41,833 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: stop_status
2023-11-26 14:37:41,833 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-26 14:37:41,834 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: stop_status
2023-11-26 14:37:41,861 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:42,301 DEBUG   SenderThread:21580 [sender.py:send():380] send: telemetry
2023-11-26 14:37:42,542 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/imwjep7k/wandb-metadata.json?Expires=1701067073&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=l%2B0bidhzu9DxIT6fsyigWCyLstdu1Zj4t%2BWDMMshx162QflKly11qXmZ0Z9QMNUZZ6oqHsIIq2m06sURBOeZKwzImEPz6busoN3a3lruUDlfl3cfaUL5gayn8n8tdz3VRVae28B6kS%2FXWzALd5wKpZTa%2BsZuvpwHYFILvfpUxfg5Pc4JTD0jzS6y%2FjHkhLJs28OpZxWHjJNXmP3YkSdXXo1lQjzW3%2B9UestDBsSsZh2vn2eEwCmK%2BFrXgLQ3ZUlNDlrZAjkmv861If6YIkZOca0Jza9Xsv9dnpPjWwdE49XuruY8mrIp16%2Bv8dGE%2FTeD%2FKt6szys8Ld31VRabUyVKA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:42,542 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1267'}
2023-11-26 14:37:42,542 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:42,645 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\conda-environment.yaml
2023-11-26 14:37:42,645 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\output.log
2023-11-26 14:37:42,646 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\wandb-metadata.json
2023-11-26 14:37:43,908 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:44,092 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/imwjep7k/wandb-metadata.json?Expires=1701067073&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=l%2B0bidhzu9DxIT6fsyigWCyLstdu1Zj4t%2BWDMMshx162QflKly11qXmZ0Z9QMNUZZ6oqHsIIq2m06sURBOeZKwzImEPz6busoN3a3lruUDlfl3cfaUL5gayn8n8tdz3VRVae28B6kS%2FXWzALd5wKpZTa%2BsZuvpwHYFILvfpUxfg5Pc4JTD0jzS6y%2FjHkhLJs28OpZxWHjJNXmP3YkSdXXo1lQjzW3%2B9UestDBsSsZh2vn2eEwCmK%2BFrXgLQ3ZUlNDlrZAjkmv861If6YIkZOca0Jza9Xsv9dnpPjWwdE49XuruY8mrIp16%2Bv8dGE%2FTeD%2FKt6szys8Ld31VRabUyVKA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:44,092 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1267'}
2023-11-26 14:37:44,092 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:44,670 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\output.log
2023-11-26 14:37:45,967 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:46,331 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:46,433 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/imwjep7k/wandb-metadata.json?Expires=1701067073&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=l%2B0bidhzu9DxIT6fsyigWCyLstdu1Zj4t%2BWDMMshx162QflKly11qXmZ0Z9QMNUZZ6oqHsIIq2m06sURBOeZKwzImEPz6busoN3a3lruUDlfl3cfaUL5gayn8n8tdz3VRVae28B6kS%2FXWzALd5wKpZTa%2BsZuvpwHYFILvfpUxfg5Pc4JTD0jzS6y%2FjHkhLJs28OpZxWHjJNXmP3YkSdXXo1lQjzW3%2B9UestDBsSsZh2vn2eEwCmK%2BFrXgLQ3ZUlNDlrZAjkmv861If6YIkZOca0Jza9Xsv9dnpPjWwdE49XuruY8mrIp16%2Bv8dGE%2FTeD%2FKt6szys8Ld31VRabUyVKA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:46,433 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1267'}
2023-11-26 14:37:46,433 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:46,433 INFO    wandb-upload_0:21580 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\anaconda\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\anaconda\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\anaconda\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "E:\anaconda\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\anaconda\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\anaconda\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\anaconda\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-11-26 14:37:48,007 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:50,079 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:50,086 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: partial_history
2023-11-26 14:37:50,087 DEBUG   SenderThread:21580 [sender.py:send():380] send: history
2023-11-26 14:37:50,087 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: summary_record
2023-11-26 14:37:50,088 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:37:50,706 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\wandb-summary.json
2023-11-26 14:37:51,453 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/imwjep7k/wandb-metadata.json?Expires=1701067073&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=l%2B0bidhzu9DxIT6fsyigWCyLstdu1Zj4t%2BWDMMshx162QflKly11qXmZ0Z9QMNUZZ6oqHsIIq2m06sURBOeZKwzImEPz6busoN3a3lruUDlfl3cfaUL5gayn8n8tdz3VRVae28B6kS%2FXWzALd5wKpZTa%2BsZuvpwHYFILvfpUxfg5Pc4JTD0jzS6y%2FjHkhLJs28OpZxWHjJNXmP3YkSdXXo1lQjzW3%2B9UestDBsSsZh2vn2eEwCmK%2BFrXgLQ3ZUlNDlrZAjkmv861If6YIkZOca0Jza9Xsv9dnpPjWwdE49XuruY8mrIp16%2Bv8dGE%2FTeD%2FKt6szys8Ld31VRabUyVKA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:51,453 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1267'}
2023-11-26 14:37:51,453 ERROR   wandb-upload_0:21580 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:52,104 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:52,115 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:52,422 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: partial_history
2023-11-26 14:37:52,423 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: partial_history
2023-11-26 14:37:52,423 DEBUG   SenderThread:21580 [sender.py:send():380] send: history
2023-11-26 14:37:52,424 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: summary_record
2023-11-26 14:37:52,424 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:37:52,425 DEBUG   SenderThread:21580 [sender.py:send():380] send: history
2023-11-26 14:37:52,425 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: summary_record
2023-11-26 14:37:52,426 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:37:52,727 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\output.log
2023-11-26 14:37:52,727 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\wandb-summary.json
2023-11-26 14:37:54,159 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:54,741 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\output.log
2023-11-26 14:37:56,197 ERROR   gpu       :21580 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:37:56,343 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: partial_history
2023-11-26 14:37:56,344 DEBUG   SenderThread:21580 [sender.py:send():380] send: history
2023-11-26 14:37:56,344 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: summary_record
2023-11-26 14:37:56,345 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:37:56,753 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\wandb-summary.json
2023-11-26 14:37:56,813 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: stop_status
2023-11-26 14:37:56,813 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-26 14:37:56,814 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: stop_status
2023-11-26 14:37:57,105 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:57,507 DEBUG   SenderThread:21580 [sender.py:send():380] send: exit
2023-11-26 14:37:57,507 INFO    SenderThread:21580 [sender.py:send_exit():585] handling exit code: 255
2023-11-26 14:37:57,507 INFO    SenderThread:21580 [sender.py:send_exit():587] handling runtime: 21
2023-11-26 14:37:57,508 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:37:57,509 INFO    SenderThread:21580 [sender.py:send_exit():593] send defer
2023-11-26 14:37:57,509 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,510 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 0
2023-11-26 14:37:57,510 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,510 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 0
2023-11-26 14:37:57,510 INFO    SenderThread:21580 [sender.py:transition_state():613] send defer: 1
2023-11-26 14:37:57,510 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,510 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 1
2023-11-26 14:37:57,510 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,510 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 1
2023-11-26 14:37:57,510 INFO    SenderThread:21580 [sender.py:transition_state():613] send defer: 2
2023-11-26 14:37:57,510 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,510 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 2
2023-11-26 14:37:57,510 INFO    HandlerThread:21580 [system_monitor.py:finish():190] Stopping system monitor
2023-11-26 14:37:57,511 DEBUG   SystemMonitor:21580 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-11-26 14:37:57,517 INFO    HandlerThread:21580 [interfaces.py:finish():202] Joined cpu monitor
2023-11-26 14:37:57,517 DEBUG   SystemMonitor:21580 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-11-26 14:37:57,517 INFO    HandlerThread:21580 [interfaces.py:finish():202] Joined disk monitor
2023-11-26 14:37:57,517 DEBUG   SystemMonitor:21580 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-11-26 14:37:57,548 INFO    HandlerThread:21580 [interfaces.py:finish():202] Joined gpu monitor
2023-11-26 14:37:57,548 INFO    HandlerThread:21580 [interfaces.py:finish():202] Joined memory monitor
2023-11-26 14:37:57,549 INFO    HandlerThread:21580 [interfaces.py:finish():202] Joined network monitor
2023-11-26 14:37:57,549 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,549 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 2
2023-11-26 14:37:57,549 INFO    SenderThread:21580 [sender.py:transition_state():613] send defer: 3
2023-11-26 14:37:57,550 DEBUG   SenderThread:21580 [sender.py:send():380] send: stats
2023-11-26 14:37:57,550 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,550 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 3
2023-11-26 14:37:57,550 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,550 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 3
2023-11-26 14:37:57,550 INFO    SenderThread:21580 [sender.py:transition_state():613] send defer: 4
2023-11-26 14:37:57,551 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,551 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 4
2023-11-26 14:37:57,551 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,551 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 4
2023-11-26 14:37:57,551 INFO    SenderThread:21580 [sender.py:transition_state():613] send defer: 5
2023-11-26 14:37:57,551 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,551 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 5
2023-11-26 14:37:57,552 DEBUG   SenderThread:21580 [sender.py:send():380] send: summary
2023-11-26 14:37:57,552 INFO    SenderThread:21580 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:37:57,553 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,553 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 5
2023-11-26 14:37:57,553 INFO    SenderThread:21580 [sender.py:transition_state():613] send defer: 6
2023-11-26 14:37:57,553 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:37:57,553 INFO    HandlerThread:21580 [handler.py:handle_request_defer():170] handle defer: 6
2023-11-26 14:37:57,553 DEBUG   SenderThread:21580 [sender.py:send_request():407] send_request: defer
2023-11-26 14:37:57,553 INFO    SenderThread:21580 [sender.py:send_request_defer():609] handle sender defer: 6
2023-11-26 14:37:57,556 DEBUG   HandlerThread:21580 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:57,758 INFO    Thread-12 :21580 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143729-imwjep7k\files\wandb-summary.json
