2024-03-13 20:40:45,439 INFO    StreamThr :27804 [internal.py:wandb_internal():86] W&B internal server running at pid: 27804, started at: 2024-03-13 20:40:45.438624
2024-03-13 20:40:45,440 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status
2024-03-13 20:40:45,445 INFO    WriterThread:27804 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\run-qh2vjlv3.wandb
2024-03-13 20:40:45,447 DEBUG   SenderThread:27804 [sender.py:send():380] send: header
2024-03-13 20:40:45,448 DEBUG   SenderThread:27804 [sender.py:send():380] send: run
2024-03-13 20:40:46,643 INFO    SenderThread:27804 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files
2024-03-13 20:40:46,644 INFO    SenderThread:27804 [sender.py:_start_run_threads():1122] run started: qh2vjlv3 with start time 1710333645.439625
2024-03-13 20:40:46,663 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 20:40:46,663 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: check_version
2024-03-13 20:40:50,855 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:40:50,871 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 20:40:50,915 DEBUG   HandlerThread:27804 [system_info.py:__init__():32] System info init
2024-03-13 20:40:50,915 DEBUG   HandlerThread:27804 [system_info.py:__init__():47] System info init done
2024-03-13 20:40:50,915 INFO    HandlerThread:27804 [system_monitor.py:start():181] Starting system monitor
2024-03-13 20:40:50,915 INFO    SystemMonitor:27804 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 20:40:50,915 INFO    HandlerThread:27804 [system_monitor.py:probe():201] Collecting system info
2024-03-13 20:40:50,920 INFO    SystemMonitor:27804 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 20:40:50,920 INFO    SystemMonitor:27804 [interfaces.py:start():190] Started disk monitoring
2024-03-13 20:40:50,921 INFO    SystemMonitor:27804 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 20:40:50,921 INFO    SystemMonitor:27804 [interfaces.py:start():190] Started memory monitoring
2024-03-13 20:40:50,936 INFO    SystemMonitor:27804 [interfaces.py:start():190] Started network monitoring
2024-03-13 20:40:50,959 DEBUG   HandlerThread:27804 [system_info.py:probe():196] Probing system
2024-03-13 20:40:50,960 DEBUG   HandlerThread:27804 [system_info.py:probe():244] Probing system done
2024-03-13 20:40:50,960 DEBUG   HandlerThread:27804 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T12:40:50.959689', 'startedAt': '2024-03-13T12:40:45.424621', 'docker': None, 'cuda': None, 'args': ('--task=W', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 178.64743423461914}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 20:40:50,960 INFO    HandlerThread:27804 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 20:40:50,960 INFO    HandlerThread:27804 [system_monitor.py:probe():214] Publishing system info
2024-03-13 20:40:50,960 DEBUG   HandlerThread:27804 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 20:40:50,961 DEBUG   HandlerThread:27804 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 20:40:50,961 DEBUG   HandlerThread:27804 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 20:40:50,970 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:40:51,682 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\requirements.txt
2024-03-13 20:40:51,682 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\conda-environment.yaml
2024-03-13 20:40:53,006 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:40:55,045 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:40:57,078 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:40:58,033 DEBUG   HandlerThread:27804 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 20:40:58,034 INFO    HandlerThread:27804 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 20:40:58,053 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:40:58,053 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:40:58,054 DEBUG   SenderThread:27804 [sender.py:send():380] send: files
2024-03-13 20:40:58,054 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 20:40:58,065 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:40:58,067 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:40:58,067 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:40:58,770 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\conda-environment.yaml
2024-03-13 20:40:58,771 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-metadata.json
2024-03-13 20:40:58,841 DEBUG   SenderThread:27804 [sender.py:send():380] send: telemetry
2024-03-13 20:40:59,106 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:40:59,784 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:01,152 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:01,800 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:01,863 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:03,183 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:05,216 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:05,415 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:05,416 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:05,416 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:05,417 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:05,824 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:07,263 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:07,346 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:07,346 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:07,347 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:07,348 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:07,349 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:07,349 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:07,350 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:07,350 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:07,351 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:07,831 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:07,832 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:09,299 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:09,853 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:10,761 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCBF7D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:41:10,761 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:41:10,762 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:41:11,335 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:11,545 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:11,546 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:11,546 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:11,547 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:11,859 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:12,557 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:13,081 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:41:13,081 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:41:13,081 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:41:13,378 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:13,477 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:13,478 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:13,479 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:13,479 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:13,480 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:13,480 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:13,480 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:13,481 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:13,885 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:13,886 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:14,900 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:15,427 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:17,454 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:17,641 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:17,642 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:17,940 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:17,940 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:17,941 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:18,933 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:18,934 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:18,934 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\config.yaml
2024-03-13 20:41:19,490 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:19,495 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:19,496 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:19,497 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:19,497 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:19,498 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:19,498 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:19,499 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:19,499 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:19,949 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:20,137 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-13 20:41:20,137 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:41:20,137 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:41:20,952 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:21,568 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:23,538 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:23,590 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:23,646 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:23,646 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:23,647 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:23,648 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:23,986 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:24,989 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:25,470 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:25,470 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:25,471 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:25,472 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:25,473 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:25,473 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:25,473 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:25,474 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:25,624 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:26,003 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:27,008 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:27,647 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:28,092 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:41:28,092 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:41:28,093 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:41:29,496 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:29,616 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:29,616 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:29,616 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:29,618 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:29,671 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:30,020 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:31,023 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:31,521 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:31,521 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:31,523 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:31,523 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:31,524 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:31,524 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:31,525 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:31,525 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:31,706 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:32,025 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:33,039 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:33,743 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:34,533 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:35,634 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:35,634 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:35,635 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:35,636 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:35,779 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:36,072 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:36,334 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE53070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:41:36,334 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:41:36,334 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:41:36,334 INFO    wandb-upload_0:27804 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000022FDCE53070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE53070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE53070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 20:41:37,086 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:37,472 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:37,473 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:37,474 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:37,474 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:37,475 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:37,475 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:37,476 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:37,476 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:37,821 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:38,091 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:39,093 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:39,861 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:40,492 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:41,602 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:41,603 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:41,603 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:41,604 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:41,896 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:42,102 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:43,102 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:41:43,103 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:41:43,103 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:41:43,119 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:43,472 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:43,473 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:43,473 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:43,474 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:43,475 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:43,475 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:43,475 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:43,476 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:43,928 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:44,133 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:45,150 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:45,495 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:45,966 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:47,601 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:47,602 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:47,602 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:47,603 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:47,999 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:48,172 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:49,174 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:49,487 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:49,488 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:49,489 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:49,489 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:49,490 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:49,491 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:49,491 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:49,491 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:50,035 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:50,179 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:50,497 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:50,959 DEBUG   SystemMonitor:27804 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 20:41:50,960 DEBUG   SenderThread:27804 [sender.py:send():380] send: stats
2024-03-13 20:41:51,183 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:52,119 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:53,613 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:53,614 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:53,614 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:53,615 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:54,155 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:54,193 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:54,222 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE37A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:41:54,222 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:41:54,223 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:41:55,198 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:55,504 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:41:55,504 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:55,505 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:55,506 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:55,506 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:55,507 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:55,507 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:55,507 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:55,508 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:41:56,176 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:56,207 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:41:57,211 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:41:58,105 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:41:58,149 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:41:58,149 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:41:58,202 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:41:59,640 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:41:59,640 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:41:59,641 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:41:59,641 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:00,230 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:00,234 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:00,654 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:01,245 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:01,453 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:01,453 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:01,454 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:01,455 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:01,456 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:01,456 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:01,456 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:01,457 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:02,249 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:02,264 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:03,264 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:04,295 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:05,618 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:05,619 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:05,619 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:05,620 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:06,307 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:06,329 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:06,625 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:07,311 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:07,460 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:07,461 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:07,461 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:07,462 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:07,463 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:07,463 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:07,463 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:07,464 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:08,337 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:08,357 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:09,340 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:10,399 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:11,570 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:11,571 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:11,571 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:11,572 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:12,421 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:12,438 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:12,584 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:13,110 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:42:13,127 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:42:13,127 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:42:13,423 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:13,424 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:13,427 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:13,457 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:13,457 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:13,458 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:13,459 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:13,459 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:13,460 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:14,376 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE37CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-03-13 20:42:14,376 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:42:14,376 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:42:14,454 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:14,472 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:15,469 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:16,508 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:17,570 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:17,571 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:17,571 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:17,572 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:18,517 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:18,535 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:18,579 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:19,469 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:19,470 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:19,471 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:19,471 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:19,472 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:19,472 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:19,473 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:19,473 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:19,532 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:19,532 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:20,569 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:20,969 DEBUG   SenderThread:27804 [sender.py:send():380] send: stats
2024-03-13 20:42:21,559 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:22,648 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:23,591 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:23,592 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:23,593 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:23,593 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:23,593 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:24,617 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:24,671 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:25,466 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:25,467 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:25,468 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:25,468 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:25,469 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:25,469 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:25,469 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:25,470 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:25,628 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:25,629 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:26,697 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:27,658 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:28,103 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:42:28,136 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:42:28,136 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:42:28,733 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:28,922 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:29,606 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:29,607 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:29,607 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:29,608 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:29,701 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:30,753 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:31,430 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:31,431 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:31,432 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:31,432 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:31,432 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:31,433 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:31,433 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:31,434 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:31,743 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:31,744 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:32,790 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:33,782 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:34,466 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:34,830 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:35,560 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:35,560 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:35,560 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:35,561 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:35,820 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:36,868 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:37,445 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:37,446 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:37,447 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:37,447 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:37,448 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:37,448 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:37,448 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:37,449 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:37,858 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:37,859 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:38,904 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:39,891 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:40,478 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:40,943 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:41,575 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:41,575 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:41,576 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:41,577 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:41,935 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:42,980 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:43,112 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:42:43,145 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:42:43,145 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:42:43,444 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:43,445 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:43,461 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:43,461 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:43,462 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:43,463 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:43,463 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:43,464 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:43,974 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:43,975 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:45,024 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:45,642 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-metadata.json?Expires=1710420061&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=V0WQ8ECl7Jhf%2Fo64hPNE6aQOXSG15a55Jw8DrLQjeFC3WdO1BJSMFzwLPhfCIoBSi4bfCwKzmRZOGMDtEb6nmxeeGdY613wlPuZ2fOtUCIqFVIMwJTMZ5szl9HkzSr8jQpEs8oO%2FKtoJYmqZz8wMrtTvqQ7GvZzJAfWbtNOD2uEMX0Cx9ivnOaCDu8uUYYkjskfMDQnejNMj8HFvfkMTYgUZLWuNKZNWmclrdsgXY94ybltYdVNRCn51OT80Z5HUA0GnUB09BPlf4xsdjWcDHKJJpnfnftduArbaRmmp324g4z2%2B%2Bi3VBiSjUjgOjt8P%2F1xM2npxqRelJCDi0szpcQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE537C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:42:45,643 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 20:42:45,643 ERROR   wandb-upload_0:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:42:46,018 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:46,480 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:47,059 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:47,576 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:47,576 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:47,577 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:47,577 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:48,046 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:49,100 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:49,490 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:49,491 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:49,491 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:49,492 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:49,493 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:49,493 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:49,493 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:49,494 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:50,088 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:50,089 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:50,981 DEBUG   SenderThread:27804 [sender.py:send():380] send: stats
2024-03-13 20:42:51,138 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:51,986 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:52,131 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:53,229 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:53,633 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:53,633 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:53,634 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:53,635 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:54,184 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:55,261 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:55,457 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:55,457 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:42:55,458 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:55,459 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:55,459 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:55,460 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:42:55,460 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:42:55,461 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:42:56,214 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:42:56,215 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:57,284 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:57,474 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:42:58,129 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:42:58,161 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:42:58,162 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:42:58,257 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:42:59,304 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:42:59,592 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:43:01,337 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:43:01,508 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:43:01,509 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:43:02,655 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:43:03,372 ERROR   gpu       :27804 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:43:05,088 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:43:05,088 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:43:05,088 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:43:05,090 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:43:05,091 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:43:05,091 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:43:05,091 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:43:05,092 DEBUG   SenderThread:27804 [sender.py:send():380] send: history
2024-03-13 20:43:05,092 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:43:05,093 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:43:05,093 DEBUG   SenderThread:27804 [sender.py:send():380] send: exit
2024-03-13 20:43:05,093 INFO    SenderThread:27804 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 20:43:05,093 INFO    SenderThread:27804 [sender.py:send_exit():587] handling runtime: 130
2024-03-13 20:43:05,094 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:43:05,094 INFO    SenderThread:27804 [sender.py:send_exit():593] send defer
2024-03-13 20:43:05,094 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 20:43:05,094 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,095 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 20:43:05,095 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,095 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 20:43:05,095 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 1
2024-03-13 20:43:05,095 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,095 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 20:43:05,095 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,095 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 20:43:05,095 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 2
2024-03-13 20:43:05,096 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,096 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 20:43:05,096 INFO    HandlerThread:27804 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 20:43:05,096 DEBUG   SystemMonitor:27804 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 20:43:05,103 DEBUG   SystemMonitor:27804 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 20:43:05,104 INFO    HandlerThread:27804 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 20:43:05,105 INFO    HandlerThread:27804 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 20:43:05,145 INFO    HandlerThread:27804 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 20:43:05,145 INFO    HandlerThread:27804 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 20:43:05,145 INFO    HandlerThread:27804 [interfaces.py:finish():202] Joined network monitor
2024-03-13 20:43:05,146 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,146 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 20:43:05,146 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 3
2024-03-13 20:43:05,146 DEBUG   SenderThread:27804 [sender.py:send():380] send: stats
2024-03-13 20:43:05,146 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,147 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 20:43:05,147 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,147 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 20:43:05,147 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 4
2024-03-13 20:43:05,147 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,147 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 20:43:05,148 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,148 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 20:43:05,148 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 5
2024-03-13 20:43:05,148 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,148 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 20:43:05,148 DEBUG   SenderThread:27804 [sender.py:send():380] send: summary
2024-03-13 20:43:05,149 INFO    SenderThread:27804 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:43:05,149 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,150 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 20:43:05,150 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 6
2024-03-13 20:43:05,150 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,150 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 20:43:05,150 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,150 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 20:43:05,150 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 7
2024-03-13 20:43:05,150 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:43:05,150 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,150 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 20:43:05,151 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,151 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 20:43:05,374 INFO    Thread-12 :27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json
2024-03-13 20:43:05,641 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 8
2024-03-13 20:43:05,641 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,641 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 20:43:05,642 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,642 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 20:43:05,642 INFO    SenderThread:27804 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 20:43:05,643 INFO    SenderThread:27804 [job_builder.py:_get_source_type():404] no source found
2024-03-13 20:43:05,643 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 9
2024-03-13 20:43:05,643 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:05,643 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 20:43:05,643 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:05,643 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 20:43:05,643 INFO    SenderThread:27804 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 20:43:06,382 INFO    SenderThread:27804 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log
2024-03-13 20:43:06,382 INFO    SenderThread:27804 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files
2024-03-13 20:43:06,383 INFO    SenderThread:27804 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\conda-environment.yaml conda-environment.yaml
2024-03-13 20:43:06,384 INFO    SenderThread:27804 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\config.yaml config.yaml
2024-03-13 20:43:06,386 INFO    SenderThread:27804 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\output.log output.log
2024-03-13 20:43:06,388 INFO    SenderThread:27804 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\requirements.txt requirements.txt
2024-03-13 20:43:06,390 INFO    SenderThread:27804 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-metadata.json wandb-metadata.json
2024-03-13 20:43:06,391 INFO    SenderThread:27804 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_204045-qh2vjlv3\files\wandb-summary.json wandb-summary.json
2024-03-13 20:43:06,392 INFO    SenderThread:27804 [sender.py:transition_state():613] send defer: 10
2024-03-13 20:43:06,392 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: defer
2024-03-13 20:43:06,393 INFO    HandlerThread:27804 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 20:43:06,394 DEBUG   SenderThread:27804 [sender.py:send_request():407] send_request: defer
2024-03-13 20:43:06,394 INFO    SenderThread:27804 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 20:43:06,394 INFO    SenderThread:27804 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 20:43:07,698 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:43:10,428 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:43:12,751 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:43:15,483 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:43:17,784 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:43:19,012 ERROR   wandb-upload_1:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/conda-environment.yaml?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZvN1z3qSNML%2BR%2FK9rvEoa4bzTehvemykmFcbj7UHQ0vpkVsO6xeZYAmfW0t9yYA40QT5fZ2hCN118nSwblMAD9i0xF6yFx7KpFBPp%2BI6CSmRxOKfUlWWovyni68bUOxmq70oLkzvjTrblKzRx2CMDXt2tzyLPhuXTiNuTQ022OsmkKHHLZNNoY5V8Ac5KZx6JD1QwFFPGzJ08H21yWn%2BA8MRAxXuHMDYZzHO9%2BNm2b1cI%2Ba0ewoQf4A1yznAvRoyPRO%2BDeDXbLUn9WiRTWMcaCEwXNr%2BSydOHBoqyDwW4Qv6M2QmqKvc547Dwj0XgNsOLJzqYOAzC7hGmLZ1pGZ2Og%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/conda-environment.yaml?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZvN1z3qSNML%2BR%2FK9rvEoa4bzTehvemykmFcbj7UHQ0vpkVsO6xeZYAmfW0t9yYA40QT5fZ2hCN118nSwblMAD9i0xF6yFx7KpFBPp%2BI6CSmRxOKfUlWWovyni68bUOxmq70oLkzvjTrblKzRx2CMDXt2tzyLPhuXTiNuTQ022OsmkKHHLZNNoY5V8Ac5KZx6JD1QwFFPGzJ08H21yWn%2BA8MRAxXuHMDYZzHO9%2BNm2b1cI%2Ba0ewoQf4A1yznAvRoyPRO%2BDeDXbLUn9WiRTWMcaCEwXNr%2BSydOHBoqyDwW4Qv6M2QmqKvc547Dwj0XgNsOLJzqYOAzC7hGmLZ1pGZ2Og%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE376D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:43:19,013 ERROR   wandb-upload_1:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 20:43:19,013 ERROR   wandb-upload_1:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:43:19,258 ERROR   wandb-upload_2:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/config.yaml?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=b%2FQrmjvn80ZOEWnX6aK1meaJ61vwmUIONFUq80ncS7rZCMZ%2BRxpv93ZWepIipRLXC8lUPI54ODc6iwFAmFNX%2B4ykyTW457tM2U2eINBNwhP5TAiTo%2FwYyx2EVqtNEJL9Pfgk0yHVi6nur48IE0M9CgOjMaIetc9AazwQgRXBCCQyiz%2FkrxXmpN2iUpl9ab8fRjGyf5qqazo2HbJk7XVHhRunb3fXLf%2FwptTOPT2hCVZYI1cRT7jSvTYIlT0%2FJ2MdJmIDxC2DfanXoClO4t6XolqIsQO90Da%2FlLF5wYghBPu2gkUUhh7pqiDVJU%2FIbmbe6bmxM60Y4gdbUNZ8ayblZQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/config.yaml?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=b%2FQrmjvn80ZOEWnX6aK1meaJ61vwmUIONFUq80ncS7rZCMZ%2BRxpv93ZWepIipRLXC8lUPI54ODc6iwFAmFNX%2B4ykyTW457tM2U2eINBNwhP5TAiTo%2FwYyx2EVqtNEJL9Pfgk0yHVi6nur48IE0M9CgOjMaIetc9AazwQgRXBCCQyiz%2FkrxXmpN2iUpl9ab8fRjGyf5qqazo2HbJk7XVHhRunb3fXLf%2FwptTOPT2hCVZYI1cRT7jSvTYIlT0%2FJ2MdJmIDxC2DfanXoClO4t6XolqIsQO90Da%2FlLF5wYghBPu2gkUUhh7pqiDVJU%2FIbmbe6bmxM60Y4gdbUNZ8ayblZQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE535E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:43:19,258 ERROR   wandb-upload_5:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-summary.json?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Lus%2ByrBjwhdjeWnBTEkoWQByYQ6aJlbQJEN6HxQx3j9POv3okUpIR6vq68CK69yrFdffDJ41C9DQBahQ0GrMp0ofDcEktNqpFKeL6qlQuKTPnR4pWAOJDGDXY7nLajBDIyqgmQ1KZbDimwBrbZ0aWmhaunK0Swnt8KHGZwuUmiigGpCLOLcELNs0Ecs8iUKknw98eJDURt9hMOW%2BsABGOj%2BdYxityRs7etmT4QwKKZWPgZBOEhRO4StEKQQaR18qtWgRynryGy5mOb1Pd1%2FuA%2FSEDRkhBU9F%2FPElmNIvB3lftzFKbRMT6yKBNU%2Be5LPewCtFn6nYwfcxUZxowcrZVQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/wandb-summary.json?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Lus%2ByrBjwhdjeWnBTEkoWQByYQ6aJlbQJEN6HxQx3j9POv3okUpIR6vq68CK69yrFdffDJ41C9DQBahQ0GrMp0ofDcEktNqpFKeL6qlQuKTPnR4pWAOJDGDXY7nLajBDIyqgmQ1KZbDimwBrbZ0aWmhaunK0Swnt8KHGZwuUmiigGpCLOLcELNs0Ecs8iUKknw98eJDURt9hMOW%2BsABGOj%2BdYxityRs7etmT4QwKKZWPgZBOEhRO4StEKQQaR18qtWgRynryGy5mOb1Pd1%2FuA%2FSEDRkhBU9F%2FPElmNIvB3lftzFKbRMT6yKBNU%2Be5LPewCtFn6nYwfcxUZxowcrZVQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE53A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:43:19,258 ERROR   wandb-upload_4:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/requirements.txt?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YNqB3ZbayMEdWGEQ6Sbe3IFhMz%2FwsLpPpasSox3G558w8Hk3rcxwYYRKfYpHJHyzTDANnc3kMK7hr8HPvtuymF4BK1ebwsN%2FH169Wi7wJFVpLA8Kj%2Fjb3WlKV3io5fhOXw8j04zxRx3%2FmJAXT4aUFES%2FpJY8548g3Tt968qa4zbBjBbMoy5%2F9qDMcUUvCLGmd1OB4trd%2F2TOPHR63OYmtRvWVUxLmAtqnv0wdFg80gdLjfmiPNi8%2F7ZGMLPSvX53tLZgnWhr3Johef2CN8gznRs89Z0X6K1F%2BtHxGzIE9Ib86NspU%2BKHfMc2NDSZ89XXTig4BQtRIffj6ODJWP2DSQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/requirements.txt?Expires=1710420189&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YNqB3ZbayMEdWGEQ6Sbe3IFhMz%2FwsLpPpasSox3G558w8Hk3rcxwYYRKfYpHJHyzTDANnc3kMK7hr8HPvtuymF4BK1ebwsN%2FH169Wi7wJFVpLA8Kj%2Fjb3WlKV3io5fhOXw8j04zxRx3%2FmJAXT4aUFES%2FpJY8548g3Tt968qa4zbBjBbMoy5%2F9qDMcUUvCLGmd1OB4trd%2F2TOPHR63OYmtRvWVUxLmAtqnv0wdFg80gdLjfmiPNi8%2F7ZGMLPSvX53tLZgnWhr3Johef2CN8gznRs89Z0X6K1F%2BtHxGzIE9Ib86NspU%2BKHfMc2NDSZ89XXTig4BQtRIffj6ODJWP2DSQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE536D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:43:19,258 ERROR   wandb-upload_2:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 20:43:19,258 ERROR   wandb-upload_5:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '207'}
2024-03-13 20:43:19,259 ERROR   wandb-upload_4:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 20:43:19,259 ERROR   wandb-upload_2:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:43:19,259 ERROR   wandb-upload_5:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:43:19,259 ERROR   wandb-upload_4:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:43:20,251 ERROR   wandb-upload_3:27804 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/output.log?Expires=1710420190&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DAu0l3t3Mu8CVZ2b2%2BzQFVm7EiNZFMAojCKMqjWRxeNgxZsvoG%2Fy193YB5zLdASMOfv3FEYNk9VQhnygh6txmewPxz1%2Fzcj6rD9v5SHxTiT1LgR04IGNFumgzEEKbfetZt%2BbWr%2FDbYbbHtpBO7K5rU3DblzD0u1V%2BzJpwukwk0iA%2B%2B0AmgJ5voW21l%2Btyzy%2FPbmcI8QrR9TigDibKL6oWiMI1yaqikdxsUA3xuptUT7RaQL32aMtxAB43S%2FvdAdnTMm2t7H%2BvuGr8ANiHjHLcZXzs%2Fwrmj%2FXCGE36AESSdH9focgOQnRN40lTLkVDXbnnm1tg%2FrXb0nA9sU5J4hUbA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/output.log?Expires=1710420190&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DAu0l3t3Mu8CVZ2b2%2BzQFVm7EiNZFMAojCKMqjWRxeNgxZsvoG%2Fy193YB5zLdASMOfv3FEYNk9VQhnygh6txmewPxz1%2Fzcj6rD9v5SHxTiT1LgR04IGNFumgzEEKbfetZt%2BbWr%2FDbYbbHtpBO7K5rU3DblzD0u1V%2BzJpwukwk0iA%2B%2B0AmgJ5voW21l%2Btyzy%2FPbmcI8QrR9TigDibKL6oWiMI1yaqikdxsUA3xuptUT7RaQL32aMtxAB43S%2FvdAdnTMm2t7H%2BvuGr8ANiHjHLcZXzs%2Fwrmj%2FXCGE36AESSdH9focgOQnRN40lTLkVDXbnnm1tg%2FrXb0nA9sU5J4hUbA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE50A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 20:43:20,251 ERROR   wandb-upload_3:27804 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1456'}
2024-03-13 20:43:20,251 ERROR   wandb-upload_3:27804 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 20:43:20,251 INFO    wandb-upload_3:27804 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000022FDCE50A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/output.log?Expires=1710420190&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DAu0l3t3Mu8CVZ2b2%2BzQFVm7EiNZFMAojCKMqjWRxeNgxZsvoG%2Fy193YB5zLdASMOfv3FEYNk9VQhnygh6txmewPxz1%2Fzcj6rD9v5SHxTiT1LgR04IGNFumgzEEKbfetZt%2BbWr%2FDbYbbHtpBO7K5rU3DblzD0u1V%2BzJpwukwk0iA%2B%2B0AmgJ5voW21l%2Btyzy%2FPbmcI8QrR9TigDibKL6oWiMI1yaqikdxsUA3xuptUT7RaQL32aMtxAB43S%2FvdAdnTMm2t7H%2BvuGr8ANiHjHLcZXzs%2Fwrmj%2FXCGE36AESSdH9focgOQnRN40lTLkVDXbnnm1tg%2FrXb0nA9sU5J4hUbA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE50A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/qh2vjlv3/output.log?Expires=1710420190&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DAu0l3t3Mu8CVZ2b2%2BzQFVm7EiNZFMAojCKMqjWRxeNgxZsvoG%2Fy193YB5zLdASMOfv3FEYNk9VQhnygh6txmewPxz1%2Fzcj6rD9v5SHxTiT1LgR04IGNFumgzEEKbfetZt%2BbWr%2FDbYbbHtpBO7K5rU3DblzD0u1V%2BzJpwukwk0iA%2B%2B0AmgJ5voW21l%2Btyzy%2FPbmcI8QrR9TigDibKL6oWiMI1yaqikdxsUA3xuptUT7RaQL32aMtxAB43S%2FvdAdnTMm2t7H%2BvuGr8ANiHjHLcZXzs%2Fwrmj%2FXCGE36AESSdH9focgOQnRN40lTLkVDXbnnm1tg%2FrXb0nA9sU5J4hUbA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022FDCE50A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 20:43:20,516 DEBUG   HandlerThread:27804 [handler.py:handle_request():144] handle_request: status_report
