2023-11-26 14:34:31,800 INFO    StreamThr :21044 [internal.py:wandb_internal():86] W&B internal server running at pid: 21044, started at: 2023-11-26 14:34:31.799215
2023-11-26 14:34:31,801 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status
2023-11-26 14:34:31,804 INFO    WriterThread:21044 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\run-h60tunz1.wandb
2023-11-26 14:34:31,806 DEBUG   SenderThread:21044 [sender.py:send():380] send: header
2023-11-26 14:34:31,806 DEBUG   SenderThread:21044 [sender.py:send():380] send: run
2023-11-26 14:34:32,525 INFO    SenderThread:21044 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files
2023-11-26 14:34:32,536 INFO    SenderThread:21044 [sender.py:_start_run_threads():1122] run started: h60tunz1 with start time 1700980471.799214
2023-11-26 14:34:32,539 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: check_version
2023-11-26 14:34:32,539 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: check_version
2023-11-26 14:34:35,389 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: run_start
2023-11-26 14:34:35,443 DEBUG   HandlerThread:21044 [system_info.py:__init__():32] System info init
2023-11-26 14:34:35,443 DEBUG   HandlerThread:21044 [system_info.py:__init__():47] System info init done
2023-11-26 14:34:35,444 INFO    HandlerThread:21044 [system_monitor.py:start():181] Starting system monitor
2023-11-26 14:34:35,444 INFO    SystemMonitor:21044 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-11-26 14:34:35,444 INFO    HandlerThread:21044 [system_monitor.py:probe():201] Collecting system info
2023-11-26 14:34:35,447 INFO    SystemMonitor:21044 [interfaces.py:start():190] Started cpu monitoring
2023-11-26 14:34:35,448 INFO    SystemMonitor:21044 [interfaces.py:start():190] Started disk monitoring
2023-11-26 14:34:35,448 INFO    SystemMonitor:21044 [interfaces.py:start():190] Started gpu monitoring
2023-11-26 14:34:35,449 INFO    SystemMonitor:21044 [interfaces.py:start():190] Started memory monitoring
2023-11-26 14:34:35,473 INFO    SystemMonitor:21044 [interfaces.py:start():190] Started network monitoring
2023-11-26 14:34:35,509 DEBUG   HandlerThread:21044 [system_info.py:probe():196] Probing system
2023-11-26 14:34:35,510 DEBUG   HandlerThread:21044 [system_info.py:probe():244] Probing system done
2023-11-26 14:34:35,510 DEBUG   HandlerThread:21044 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2023-11-26T06:34:35.510016', 'startedAt': '2023-11-26T06:34:31.776986', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train real.py', 'codePathLocal': 'train real.py', 'codePath': 'train real.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2555.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 2555.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 103.9238395690918}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2023-11-26 14:34:35,510 INFO    HandlerThread:21044 [system_monitor.py:probe():211] Finished collecting system info
2023-11-26 14:34:35,510 INFO    HandlerThread:21044 [system_monitor.py:probe():214] Publishing system info
2023-11-26 14:34:35,510 DEBUG   HandlerThread:21044 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-11-26 14:34:35,511 DEBUG   HandlerThread:21044 [system_info.py:_save_pip():68] Saving pip packages done
2023-11-26 14:34:35,511 DEBUG   HandlerThread:21044 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-11-26 14:34:35,534 ERROR   gpu       :21044 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:34:35,562 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\requirements.txt
2023-11-26 14:34:35,562 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\conda-environment.yaml
2023-11-26 14:34:37,581 ERROR   gpu       :21044 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:34:39,636 ERROR   gpu       :21044 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:34:41,510 DEBUG   HandlerThread:21044 [system_info.py:_save_conda():87] Saving conda packages done
2023-11-26 14:34:41,511 INFO    HandlerThread:21044 [system_monitor.py:probe():216] Finished publishing system info
2023-11-26 14:34:41,527 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:34:41,527 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:34:41,527 DEBUG   SenderThread:21044 [sender.py:send():380] send: files
2023-11-26 14:34:41,527 INFO    SenderThread:21044 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-11-26 14:34:41,536 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: stop_status
2023-11-26 14:34:41,536 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: stop_status
2023-11-26 14:34:41,537 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: internal_messages
2023-11-26 14:34:41,660 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\conda-environment.yaml
2023-11-26 14:34:41,660 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\wandb-metadata.json
2023-11-26 14:34:41,693 ERROR   gpu       :21044 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-11-26 14:34:42,053 DEBUG   SenderThread:21044 [sender.py:send():380] send: telemetry
2023-11-26 14:34:42,066 DEBUG   SenderThread:21044 [sender.py:send():380] send: exit
2023-11-26 14:34:42,066 INFO    SenderThread:21044 [sender.py:send_exit():585] handling exit code: 1
2023-11-26 14:34:42,066 INFO    SenderThread:21044 [sender.py:send_exit():587] handling runtime: 6
2023-11-26 14:34:42,067 INFO    SenderThread:21044 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:34:42,068 INFO    SenderThread:21044 [sender.py:send_exit():593] send defer
2023-11-26 14:34:42,068 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,068 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 0
2023-11-26 14:34:42,068 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,069 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 0
2023-11-26 14:34:42,069 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 1
2023-11-26 14:34:42,069 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,069 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 1
2023-11-26 14:34:42,069 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,069 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 1
2023-11-26 14:34:42,069 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 2
2023-11-26 14:34:42,069 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,069 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 2
2023-11-26 14:34:42,069 INFO    HandlerThread:21044 [system_monitor.py:finish():190] Stopping system monitor
2023-11-26 14:34:42,070 DEBUG   SystemMonitor:21044 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-11-26 14:34:42,070 INFO    HandlerThread:21044 [interfaces.py:finish():202] Joined cpu monitor
2023-11-26 14:34:42,075 DEBUG   SystemMonitor:21044 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-11-26 14:34:42,076 INFO    HandlerThread:21044 [interfaces.py:finish():202] Joined disk monitor
2023-11-26 14:34:42,076 DEBUG   SystemMonitor:21044 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-11-26 14:34:42,105 INFO    HandlerThread:21044 [interfaces.py:finish():202] Joined gpu monitor
2023-11-26 14:34:42,105 INFO    HandlerThread:21044 [interfaces.py:finish():202] Joined memory monitor
2023-11-26 14:34:42,105 INFO    HandlerThread:21044 [interfaces.py:finish():202] Joined network monitor
2023-11-26 14:34:42,106 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,106 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 2
2023-11-26 14:34:42,106 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 3
2023-11-26 14:34:42,106 DEBUG   SenderThread:21044 [sender.py:send():380] send: stats
2023-11-26 14:34:42,107 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,107 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 3
2023-11-26 14:34:42,107 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,107 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 3
2023-11-26 14:34:42,107 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 4
2023-11-26 14:34:42,107 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,107 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 4
2023-11-26 14:34:42,108 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,108 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 4
2023-11-26 14:34:42,108 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 5
2023-11-26 14:34:42,108 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,108 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 5
2023-11-26 14:34:42,108 DEBUG   SenderThread:21044 [sender.py:send():380] send: summary
2023-11-26 14:34:42,109 INFO    SenderThread:21044 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-11-26 14:34:42,109 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,109 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 5
2023-11-26 14:34:42,109 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 6
2023-11-26 14:34:42,109 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,110 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 6
2023-11-26 14:34:42,110 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,110 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 6
2023-11-26 14:34:42,112 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:34:42,237 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:42,237 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:34:42,237 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:42,369 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 7
2023-11-26 14:34:42,370 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:42,370 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 7
2023-11-26 14:34:42,370 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:42,370 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 7
2023-11-26 14:34:42,673 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\config.yaml
2023-11-26 14:34:42,673 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\wandb-summary.json
2023-11-26 14:34:42,674 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\output.log
2023-11-26 14:34:42,942 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: poll_exit
2023-11-26 14:34:43,578 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:43,578 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:34:43,578 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:44,701 INFO    Thread-12 :21044 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\output.log
2023-11-26 14:34:45,893 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:45,893 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:34:45,893 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:45,893 INFO    wandb-upload_0:21044 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\anaconda\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\anaconda\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\anaconda\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "E:\anaconda\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "E:\anaconda\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\anaconda\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\anaconda\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\anaconda\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-11-26 14:34:46,086 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 8
2023-11-26 14:34:46,086 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: poll_exit
2023-11-26 14:34:46,086 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:46,087 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 8
2023-11-26 14:34:46,087 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:46,087 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 8
2023-11-26 14:34:46,087 INFO    SenderThread:21044 [job_builder.py:build():281] Attempting to build job artifact
2023-11-26 14:34:46,088 INFO    SenderThread:21044 [job_builder.py:_get_source_type():404] no source found
2023-11-26 14:34:46,088 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 9
2023-11-26 14:34:46,088 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:46,088 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 9
2023-11-26 14:34:46,089 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:46,089 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 9
2023-11-26 14:34:46,089 INFO    SenderThread:21044 [dir_watcher.py:finish():358] shutting down directory watcher
2023-11-26 14:34:46,708 INFO    SenderThread:21044 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\output.log
2023-11-26 14:34:46,709 INFO    SenderThread:21044 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files
2023-11-26 14:34:46,710 INFO    SenderThread:21044 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\conda-environment.yaml conda-environment.yaml
2023-11-26 14:34:46,710 INFO    SenderThread:21044 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\config.yaml config.yaml
2023-11-26 14:34:46,712 INFO    SenderThread:21044 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\output.log output.log
2023-11-26 14:34:46,714 INFO    SenderThread:21044 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\requirements.txt requirements.txt
2023-11-26 14:34:46,717 INFO    SenderThread:21044 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\wandb-metadata.json wandb-metadata.json
2023-11-26 14:34:46,717 INFO    SenderThread:21044 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20231126_143431-h60tunz1\files\wandb-summary.json wandb-summary.json
2023-11-26 14:34:46,719 INFO    SenderThread:21044 [sender.py:transition_state():613] send defer: 10
2023-11-26 14:34:46,719 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: defer
2023-11-26 14:34:46,719 INFO    HandlerThread:21044 [handler.py:handle_request_defer():170] handle defer: 10
2023-11-26 14:34:46,721 DEBUG   SenderThread:21044 [sender.py:send_request():407] send_request: defer
2023-11-26 14:34:46,721 INFO    SenderThread:21044 [sender.py:send_request_defer():609] handle sender defer: 10
2023-11-26 14:34:46,721 INFO    SenderThread:21044 [file_pusher.py:finish():175] shutting down file pusher
2023-11-26 14:34:47,180 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:47,180 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:34:47,181 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:47,264 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:47,264 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:34:47,264 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:47,339 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:47,339 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:34:47,339 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:47,346 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:47,346 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:34:47,346 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:47,388 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:47,388 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:34:47,388 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:47,963 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:34:48,563 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:48,564 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:34:48,564 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:48,613 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:48,613 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:34:48,613 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:48,744 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:48,744 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:34:48,744 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:48,769 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:48,769 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:34:48,769 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:48,776 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:48,776 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:34:48,776 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:50,775 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:50,775 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:34:50,775 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:51,035 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:51,035 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:34:51,035 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:51,064 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:51,064 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:34:51,064 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:51,072 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:51,072 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:34:51,072 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:51,135 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:51,135 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:34:51,135 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:51,351 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:51,352 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:34:51,352 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:51,774 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:34:53,027 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:34:55,506 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:55,506 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:34:55,506 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:55,663 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:55,663 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:34:55,663 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:55,715 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:55,715 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:34:55,715 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:56,092 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:56,092 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:34:56,093 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:56,242 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:34:56,242 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:34:56,242 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:34:56,809 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:34:58,064 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:00,262 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:00,262 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:35:00,262 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:01,871 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:03,104 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:04,907 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:04,907 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:35:04,907 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:05,041 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:05,041 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:35:05,041 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:05,184 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:05,184 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:35:05,184 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:05,894 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:05,894 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:35:05,894 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:06,203 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:06,203 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:35:06,203 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:06,928 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:08,163 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:11,972 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:13,206 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:17,018 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:17,524 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:17,524 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:35:17,524 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:18,242 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:22,064 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:22,111 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:22,111 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:35:22,111 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:22,435 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:22,435 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:35:22,435 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:22,562 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:22,562 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:35:22,562 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:22,846 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:22,847 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:35:22,847 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:23,275 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:23,474 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:23,474 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:35:23,474 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:27,104 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:28,325 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:32,166 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:33,380 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:37,216 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:38,436 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:42,258 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:43,482 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:47,295 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:48,542 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:52,342 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:53,591 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:35:54,766 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:54,766 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:35:54,766 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:55,441 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:55,441 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:35:55,442 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:55,791 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:55,792 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:35:55,792 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:57,401 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:35:58,562 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:35:58,562 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:35:58,562 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:35:58,643 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:00,767 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:36:00,767 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:36:00,767 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:36:02,450 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:03,181 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:36:03,181 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:36:03,181 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:36:03,703 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:07,496 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:08,747 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:12,558 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:13,807 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:17,618 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:18,862 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:22,671 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:23,919 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:27,726 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:28,985 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:32,784 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:34,038 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:37,819 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:39,074 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:42,878 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:44,137 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:47,919 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:49,160 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:52,972 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:54,219 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:36:58,019 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:36:59,267 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:00,246 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:00,247 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:37:00,247 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:03,088 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:04,325 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:06,110 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:06,111 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:37:06,111 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:07,231 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:07,231 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:37:07,231 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:08,118 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:09,370 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:13,158 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:13,591 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:13,591 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:37:13,591 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:14,422 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:16,195 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:16,195 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:37:16,195 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:16,303 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:37:16,303 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:37:16,303 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:37:18,206 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:19,457 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:23,257 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:24,494 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:28,311 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:29,548 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:33,368 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:34,601 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:38,400 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:39,633 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:43,453 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:44,685 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:48,499 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:49,708 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:53,524 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:54,740 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:37:58,560 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:37:59,776 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:03,617 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:04,832 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:08,640 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:09,876 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:13,681 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:14,925 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:18,744 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:19,975 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:23,779 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:25,015 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:28,835 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:30,067 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:33,893 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:35,114 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:38,943 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:40,179 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:44,005 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:45,241 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:49,052 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:50,272 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:54,099 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:38:55,332 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:38:59,160 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:00,383 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:04,210 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:05,415 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:09,251 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:10,472 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:14,318 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:15,534 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:18,250 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-metadata.json?Expires=1701066893&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=BTNBkyn6S2skvKZgUldu4iNFXyDKfQ8ICAhV9E8E8Yex4l8%2F2JyFfraGUVfqvkkwRtTL7NTzDAIwSt4kQ5T0hZaycVEIaLsV9KX%2BVxty%2FEU9nCv3q9MfAHwlZrjFT7fYmVmMRlu1zgWi%2FL9FpqnTpmGZ3CG0noa%2FXVL9fvb%2FPw70AW8GiUtcwp32t54iO7gVRCtO7%2FsxKpoKu3M6plIgRFmOZgGSPlL77cDexFgUZIEJcBnBXhNW%2BKNEdi2gGtScZ943prOzZqVVBYku3Ur2HEZRieIpGn6msaDkQP3fqI6KBFSu0l9fiZITWtt3JQnbvajPjk44Vlf%2FNnrQImaSPA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:39:18,250 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1281'}
2023-11-26 14:39:18,250 ERROR   wandb-upload_0:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:39:19,368 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:20,587 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:24,423 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:24,749 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/requirements.txt?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HWdYeNyJnewpS4ooY4asxtJjggBAD4rF7CXm9TmpfZjlWf%2FG%2FpfLwB77or4swL6lckm%2FtRxN0GXJeY7kjI2MOaUTqAd9BfzYj3oLC1HKCr%2BB7x8hZZ5kzuJKKxJY9ifEX%2FmqSTDPbB1emBUOcw9MBzfo3bNruXytDWf6vqvuxhyrNRA5uo981iFWr5z2N2RsestzeRXu7oe%2FOCUgeaYjSKFLItm4hGHcom%2FkV81DFWlzJqO%2F3QKU9sjQ5gLpEo2SasJ5wSsEb9kcEvbgLT714nBFlqIYDlF4htSphFyyfUT7AAx8tO3N%2BZ%2Fwt3LWTH%2FQDyj7GBFbNaUk9%2B82iP%2BNUA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:39:24,749 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2023-11-26 14:39:24,749 ERROR   wandb-upload_4:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:39:25,639 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:28,029 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/output.log?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dO1nrkUfeSIhUBN2RXh7wWsRi0%2Ff20s4IHOaJizc3luh12GBOhP1kmoritszNij6cD3daWJ%2Bp%2FEOwLkNpyA%2Fa1XMYT07QlmqoBgI9Ef9VyeuVdCiCg9yOzecJoFw6lEW6xmsFW4B0KOtoHkzUmI%2FTGKpWRCUlL6TV62%2FwVzYC%2BLtEKQqIKC6qHeor2Unt8WkQIJk8e%2F8nWact943TesdXqSpdBRuP6662%2FF0bzlja%2BMU5FGyHZEjSCei7QR%2FesFm33AdRky5KnDQFgh8hwYnxCG0J8n12TjnJiGYA5otTEKWsVp%2BPbooUZU7FmBPvbIbYpDKihAOwlikzdoa6sx%2FqA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:39:28,029 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1906'}
2023-11-26 14:39:28,029 ERROR   wandb-upload_3:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:39:29,462 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:30,697 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:34,507 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:35,753 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:39,548 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:40,774 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:44,604 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:45,838 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:46,707 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/config.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XPW8XeTbwgofkKk8fI4ZWzUAHUK1IWNE871t7J0JbLC9FfhlEivfgDnLLmhGccu0Ko35wHui57nobh4mTnZ6Gy6WukcHh9qD36KglvPOx7Enni2NBiDJuU7jqc%2FalOdGQLm9tUNcGKkbtyyuGGCTqQqSJ0b93uL%2BmGa6geZuTCmiaSxac07eP6QpEHE4l%2B%2BmluqN%2BDTZ6gd10pJwOp8Ul8GtINJ%2B6qhBECmnFjZ4gRxH5f%2BysHrASzn5M0kwBBxi0rl3gwI9DJnNzWQBdvrKt0VPbdlkCj3ydOg%2FIm1nC0W4C4%2Fd6sfkIQMR18mSdoXiPl6F5JN%2Fp3lOt8NRIbFUJA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:39:46,707 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '432'}
2023-11-26 14:39:46,707 ERROR   wandb-upload_2:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:39:48,920 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/wandb-summary.json?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=fa6NrKu2MwhJrUb3yo0bfF8IoVWhOuyHtCFj8kVUHnY%2BnwFqBv9boO6EO3OkEhz%2BUur0vqw1nwp77xCxz4JO0zSWASeh6mN52mosoj2YCmTD1q%2FO9TDq5t90g9xka2AdCXUf1Ou%2FoobYB9QsQ4INk01%2BlUHnw2IckRJBMsoUy%2Ffvjin7OrGpDJIglyODBM6ieiKGYRm5Yh8IneQdoYDUYaQG3ssZEpPS%2BgHPc4p8NMUXwRtWuOswA9VAYQivmqLbVrPrO8B1tWTfu6SS%2BDRwZsBddIraN9J6hrGMYYMwgCOjp%2BuGFZtFL%2B3FC516UxO%2BP%2BEyZgmTRNDJbDIQCIrT4Q%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:39:48,920 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2023-11-26 14:39:48,920 ERROR   wandb-upload_5:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:39:49,631 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:50,880 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:52,408 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/h60tunz1/conda-environment.yaml?Expires=1701066898&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hZhA497eWkY%2F%2BbeYeDbn7kvEb0vAtdfZ0eOxkJraLR60IEOARbjgJFIdHfJul%2BfEo8vB4xzgPOt4xSD81Hj27RsO%2BfTDzkD08YlsnZQ%2BLWZTRfdD%2BORum9ObQk4cJdIB2MZBgN5FuplJSeQxuTRs%2Fj63QctzsaKqg%2F1CqsC3l%2FXgdjc3h41acadcYzHssXq41T%2B7rk8NXdjqJEr6eJHrx%2BZ3Mv9CmjW2OdIMIREGNOlDcWBcf1KylbbJ57UX%2B4ia%2Bx2GwLFSoZZ%2BoAzhCry3T7rVskp4gLnUyR7kIY83orfsskETH7IvIazP7e9hTk0BjN7BggJCp%2BRan3jaxnqUBw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2023-11-26 14:39:52,408 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2023-11-26 14:39:52,408 ERROR   wandb-upload_1:21044 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-26 14:39:54,688 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:39:55,947 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
2023-11-26 14:39:59,739 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: status_report
2023-11-26 14:40:00,988 DEBUG   HandlerThread:21044 [handler.py:handle_request():144] handle_request: keepalive
