2024-03-13 20:05:14,694 INFO    StreamThr :28112 [internal.py:wandb_internal():86] W&B internal server running at pid: 28112, started at: 2024-03-13 20:05:14.693127
2024-03-13 20:05:14,695 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status
2024-03-13 20:05:14,701 INFO    WriterThread:28112 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\run-rubt40t7.wandb
2024-03-13 20:05:14,703 DEBUG   SenderThread:28112 [sender.py:send():380] send: header
2024-03-13 20:05:14,704 DEBUG   SenderThread:28112 [sender.py:send():380] send: run
2024-03-13 20:05:15,350 INFO    SenderThread:28112 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files
2024-03-13 20:05:15,350 INFO    SenderThread:28112 [sender.py:_start_run_threads():1122] run started: rubt40t7 with start time 1710331514.694127
2024-03-13 20:05:15,370 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 20:05:15,371 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: check_version
2024-03-13 20:05:15,582 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 20:05:15,626 DEBUG   HandlerThread:28112 [system_info.py:__init__():32] System info init
2024-03-13 20:05:15,626 DEBUG   HandlerThread:28112 [system_info.py:__init__():47] System info init done
2024-03-13 20:05:15,626 INFO    HandlerThread:28112 [system_monitor.py:start():181] Starting system monitor
2024-03-13 20:05:15,627 INFO    SystemMonitor:28112 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 20:05:15,627 INFO    HandlerThread:28112 [system_monitor.py:probe():201] Collecting system info
2024-03-13 20:05:15,633 INFO    SystemMonitor:28112 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 20:05:15,633 INFO    SystemMonitor:28112 [interfaces.py:start():190] Started disk monitoring
2024-03-13 20:05:15,634 INFO    SystemMonitor:28112 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 20:05:15,635 INFO    SystemMonitor:28112 [interfaces.py:start():190] Started memory monitoring
2024-03-13 20:05:15,664 INFO    SystemMonitor:28112 [interfaces.py:start():190] Started network monitoring
2024-03-13 20:05:15,673 DEBUG   HandlerThread:28112 [system_info.py:probe():196] Probing system
2024-03-13 20:05:15,674 DEBUG   HandlerThread:28112 [system_info.py:probe():244] Probing system done
2024-03-13 20:05:15,674 DEBUG   HandlerThread:28112 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T12:05:15.674909', 'startedAt': '2024-03-13T12:05:14.678124', 'docker': None, 'cuda': None, 'args': ('--task=P', '--weather=rainy'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 189.8971405029297}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 20:05:15,674 INFO    HandlerThread:28112 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 20:05:15,674 INFO    HandlerThread:28112 [system_monitor.py:probe():214] Publishing system info
2024-03-13 20:05:15,674 DEBUG   HandlerThread:28112 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 20:05:15,675 DEBUG   HandlerThread:28112 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 20:05:15,675 DEBUG   HandlerThread:28112 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 20:05:15,693 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:16,356 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\requirements.txt
2024-03-13 20:05:16,357 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\conda-environment.yaml
2024-03-13 20:05:17,728 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:19,768 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:21,807 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:23,212 DEBUG   HandlerThread:28112 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 20:05:23,213 INFO    HandlerThread:28112 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 20:05:23,237 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:05:23,237 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:05:23,238 DEBUG   SenderThread:28112 [sender.py:send():380] send: files
2024-03-13 20:05:23,238 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 20:05:23,251 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 20:05:23,251 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: stop_status
2024-03-13 20:05:23,252 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:05:23,388 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\conda-environment.yaml
2024-03-13 20:05:23,388 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-metadata.json
2024-03-13 20:05:23,850 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:24,167 INFO    wandb-upload_0:28112 [upload_job.py:push():131] Uploaded file C:\Users\lenovo\AppData\Local\Temp\tmpkisrmydwwandb\vto9240y-wandb-metadata.json
2024-03-13 20:05:25,900 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:27,927 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:28,309 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:05:29,961 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:31,992 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:33,109 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:33,352 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:05:34,023 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:36,062 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:36,078 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:36,079 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:38,092 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:38,265 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:05:40,134 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:40,813 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:42,163 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:42,957 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:42,958 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:43,404 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:05:44,202 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:44,872 DEBUG   SenderThread:28112 [sender.py:send():380] send: telemetry
2024-03-13 20:05:44,873 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:05:44,874 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:44,874 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:44,875 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:44,876 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:44,876 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:44,877 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:44,877 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:44,877 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:44,878 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:44,879 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:44,879 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:44,879 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:44,880 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:44,880 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:44,881 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:44,881 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:44,881 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:44,882 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:45,587 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:05:45,588 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:05:46,292 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:47,594 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:05:47,672 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:47,673 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:47,673 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:47,674 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:48,326 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:48,421 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:05:48,596 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:05:49,599 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:05:49,740 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:49,741 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:49,741 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:49,742 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:49,743 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:49,743 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:49,743 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:49,744 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:50,347 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:50,616 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:05:50,758 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:05:51,626 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:05:52,377 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:53,275 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:05:54,401 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:54,473 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:54,474 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:54,474 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:54,475 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:54,668 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:05:55,683 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:05:56,438 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:56,499 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:05:56,584 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:56,584 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:05:56,585 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:56,586 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:56,586 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:56,587 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:05:56,587 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:05:56,588 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:05:56,691 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:05:58,480 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:05:58,520 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:05:59,701 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:00,515 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:01,336 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:01,336 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:01,337 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:01,337 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:01,716 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:06:02,353 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:06:02,546 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:03,392 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:03,393 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:03,394 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:03,394 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:03,395 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:03,396 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:03,396 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:03,396 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:03,545 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:03,734 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:03,735 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:06:04,585 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:05,743 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:05,886 WARNING FileStreamThread:28112 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001B802F7ECE0>>, timeout=180), args: ('https://api.wandb.ai/files/princeporch/uncategorized/rubt40t7/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"loss": 6.884834289550781, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5, "Test loss": 0.10974992227554321, "Epoch": 1, "Test Accuracy": 0.0}']}, 'wandb-history.jsonl': {'offset': 1, 'content': ['{"Test loss": 0.11310945415496826, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 1}', '{"Test Accuracy": 0.0, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 2}', '{"loss": 6.884834289550781, "_timestamp": 1710331540.8136535, "_runtime": 26.119526386260986, "_step": 3}', '{"Test loss": 0.10974992227554321, "Epoch": 1, "_timestamp": 1710331542.956685, "_runtime": 28.262557983398438, "_step": 4}', '{"Test Accuracy": 0.0, "Epoch": 1, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5}']}, 'output.log': {'offset': 0, 'content': ['2024-03-13T12:05:46.878008 当前脚本的参数如下：\n', "2024-03-13T12:05:46.878008 Namespace(batch_size=64, img_size=64, input_size=64, epochs=20, learning_rate=1e-06, weather='rainy', task='P', model='resnet18', mixNum=0)\n", '2024-03-13T12:05:46.878008 当前训练<雨天-车位分类器>\n', '2024-03-13T12:05:46.878008 EPOCH:0\t\tLOSS:7.051665306091309\n', '2024-03-13T12:05:46.878008 Epoch:0\t\tACCURACY:0.00%\n', '2024-03-13T12:05:46.878008 EPOCH:1\t\tLOSS:6.884834289550781\n', '2024-03-13T12:05:46.878008 Epoch:1\t\tACCURACY:0.00%\n']}}, 'dropped': 0}}
2024-03-13 20:06:06,617 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:07,412 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:06:08,102 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:08,103 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:08,103 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:08,104 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:08,290 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:06:08,662 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:08,753 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:06:09,755 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:10,253 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:10,253 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:10,254 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:10,255 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:10,255 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:10,256 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:10,256 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:10,257 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:10,695 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:10,758 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:06:11,761 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:12,731 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:13,273 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:06:13,575 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:14,772 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:14,985 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:14,986 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:14,986 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:14,987 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:15,673 DEBUG   SystemMonitor:28112 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 20:06:15,675 DEBUG   SenderThread:28112 [sender.py:send():380] send: stats
2024-03-13 20:06:15,769 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:06:16,875 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:17,108 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:17,109 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:17,110 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:17,110 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:17,111 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:17,112 DEBUG   SenderThread:28112 [sender.py:send():380] send: history
2024-03-13 20:06:17,112 DEBUG   SenderThread:28112 [sender.py:send_request():407] send_request: summary_record
2024-03-13 20:06:17,112 INFO    SenderThread:28112 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 20:06:17,809 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:17,810 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\wandb-summary.json
2024-03-13 20:06:18,619 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:18,913 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:19,130 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 20:06:19,856 INFO    Thread-12 :28112 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_200514-rubt40t7\files\output.log
2024-03-13 20:06:20,939 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:21,867 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:22,970 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:23,300 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:06:23,983 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:23,984 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:25,000 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:27,032 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:27,060 WARNING FileStreamThread:28112 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001B802F7ECE0>>, timeout=180), args: ('https://api.wandb.ai/files/princeporch/uncategorized/rubt40t7/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"loss": 6.884834289550781, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5, "Test loss": 0.10974992227554321, "Epoch": 1, "Test Accuracy": 0.0}']}, 'wandb-history.jsonl': {'offset': 1, 'content': ['{"Test loss": 0.11310945415496826, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 1}', '{"Test Accuracy": 0.0, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 2}', '{"loss": 6.884834289550781, "_timestamp": 1710331540.8136535, "_runtime": 26.119526386260986, "_step": 3}', '{"Test loss": 0.10974992227554321, "Epoch": 1, "_timestamp": 1710331542.956685, "_runtime": 28.262557983398438, "_step": 4}', '{"Test Accuracy": 0.0, "Epoch": 1, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5}']}, 'output.log': {'offset': 0, 'content': ['2024-03-13T12:05:46.878008 当前脚本的参数如下：\n', "2024-03-13T12:05:46.878008 Namespace(batch_size=64, img_size=64, input_size=64, epochs=20, learning_rate=1e-06, weather='rainy', task='P', model='resnet18', mixNum=0)\n", '2024-03-13T12:05:46.878008 当前训练<雨天-车位分类器>\n', '2024-03-13T12:05:46.878008 EPOCH:0\t\tLOSS:7.051665306091309\n', '2024-03-13T12:05:46.878008 Epoch:0\t\tACCURACY:0.00%\n', '2024-03-13T12:05:46.878008 EPOCH:1\t\tLOSS:6.884834289550781\n', '2024-03-13T12:05:46.878008 Epoch:1\t\tACCURACY:0.00%\n']}}, 'dropped': 0}}
2024-03-13 20:06:28,686 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:28,703 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:29,059 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:30,776 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:30,777 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:31,094 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:33,128 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:33,702 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:35,163 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:35,485 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:37,204 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:37,623 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:37,624 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:38,302 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:06:39,240 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:41,271 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:42,325 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:43,305 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:43,761 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:44,380 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:44,381 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:45,340 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:47,429 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:48,799 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:49,243 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:49,461 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:50,569 WARNING FileStreamThread:28112 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001B802F7ECE0>>, timeout=180), args: ('https://api.wandb.ai/files/princeporch/uncategorized/rubt40t7/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"loss": 6.884834289550781, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5, "Test loss": 0.10974992227554321, "Epoch": 1, "Test Accuracy": 0.0}']}, 'wandb-history.jsonl': {'offset': 1, 'content': ['{"Test loss": 0.11310945415496826, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 1}', '{"Test Accuracy": 0.0, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 2}', '{"loss": 6.884834289550781, "_timestamp": 1710331540.8136535, "_runtime": 26.119526386260986, "_step": 3}', '{"Test loss": 0.10974992227554321, "Epoch": 1, "_timestamp": 1710331542.956685, "_runtime": 28.262557983398438, "_step": 4}', '{"Test Accuracy": 0.0, "Epoch": 1, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5}']}, 'output.log': {'offset': 0, 'content': ['2024-03-13T12:05:46.878008 当前脚本的参数如下：\n', "2024-03-13T12:05:46.878008 Namespace(batch_size=64, img_size=64, input_size=64, epochs=20, learning_rate=1e-06, weather='rainy', task='P', model='resnet18', mixNum=0)\n", '2024-03-13T12:05:46.878008 当前训练<雨天-车位分类器>\n', '2024-03-13T12:05:46.878008 EPOCH:0\t\tLOSS:7.051665306091309\n', '2024-03-13T12:05:46.878008 Epoch:0\t\tACCURACY:0.00%\n', '2024-03-13T12:05:46.878008 EPOCH:1\t\tLOSS:6.884834289550781\n', '2024-03-13T12:05:46.878008 Epoch:1\t\tACCURACY:0.00%\n']}}, 'dropped': 0}}
2024-03-13 20:06:51,485 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:51,485 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:51,496 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:53,304 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:06:53,534 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:55,559 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:56,223 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:57,577 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:06:58,367 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:58,368 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:06:58,865 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:06:59,605 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:01,632 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:03,123 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:03,662 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:03,895 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:05,217 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:05,219 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:05,692 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:07,743 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:08,323 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:07:09,768 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:09,934 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:11,811 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:12,067 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:12,067 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:13,843 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:13,984 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:15,887 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:16,799 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:17,975 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:18,070 WARNING FileStreamThread:28112 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001B802F7ECE0>>, timeout=180), args: ('https://api.wandb.ai/files/princeporch/uncategorized/rubt40t7/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"loss": 6.884834289550781, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5, "Test loss": 0.10974992227554321, "Epoch": 1, "Test Accuracy": 0.0}']}, 'wandb-history.jsonl': {'offset': 1, 'content': ['{"Test loss": 0.11310945415496826, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 1}', '{"Test Accuracy": 0.0, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 2}', '{"loss": 6.884834289550781, "_timestamp": 1710331540.8136535, "_runtime": 26.119526386260986, "_step": 3}', '{"Test loss": 0.10974992227554321, "Epoch": 1, "_timestamp": 1710331542.956685, "_runtime": 28.262557983398438, "_step": 4}', '{"Test Accuracy": 0.0, "Epoch": 1, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5}']}, 'output.log': {'offset': 0, 'content': ['2024-03-13T12:05:46.878008 当前脚本的参数如下：\n', "2024-03-13T12:05:46.878008 Namespace(batch_size=64, img_size=64, input_size=64, epochs=20, learning_rate=1e-06, weather='rainy', task='P', model='resnet18', mixNum=0)\n", '2024-03-13T12:05:46.878008 当前训练<雨天-车位分类器>\n', '2024-03-13T12:05:46.878008 EPOCH:0\t\tLOSS:7.051665306091309\n', '2024-03-13T12:05:46.878008 Epoch:0\t\tACCURACY:0.00%\n', '2024-03-13T12:05:46.878008 EPOCH:1\t\tLOSS:6.884834289550781\n', '2024-03-13T12:05:46.878008 Epoch:1\t\tACCURACY:0.00%\n']}}, 'dropped': 0}}
2024-03-13 20:07:18,918 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:18,918 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:19,009 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:19,565 INFO    SenderThread:28112 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "E:\anaconda\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "E:\anaconda\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "E:\anaconda\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "E:\anaconda\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "E:\anaconda\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "E:\anaconda\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "E:\anaconda\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "E:\anaconda\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-03-13 20:07:19,997 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:22,030 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:23,333 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:07:23,613 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:24,052 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:25,734 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:25,735 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:26,082 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:28,113 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:29,032 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:30,149 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:30,520 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:32,177 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:32,732 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:32,732 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:34,074 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:34,206 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:36,255 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:37,396 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:38,286 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:38,348 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 20:07:39,535 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:39,536 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:40,327 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:42,359 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:44,140 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:44,393 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:44,398 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:46,430 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:46,510 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:46,511 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 20:07:47,696 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 20:07:48,535 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:50,567 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:52,596 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:52,728 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:54,625 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:56,666 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:07:56,857 WARNING FileStreamThread:28112 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/princeporch/uncategorized/rubt40t7/file_stream (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B80355BDC0>, 'Connection to api.wandb.ai timed out. (connect timeout=180)')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001B802F7ECE0>>, timeout=180), args: ('https://api.wandb.ai/files/princeporch/uncategorized/rubt40t7/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"loss": 6.884834289550781, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5, "Test loss": 0.10974992227554321, "Epoch": 1, "Test Accuracy": 0.0}']}, 'wandb-history.jsonl': {'offset': 1, 'content': ['{"Test loss": 0.11310945415496826, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 1}', '{"Test Accuracy": 0.0, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 2}', '{"loss": 6.884834289550781, "_timestamp": 1710331540.8136535, "_runtime": 26.119526386260986, "_step": 3}', '{"Test loss": 0.10974992227554321, "Epoch": 1, "_timestamp": 1710331542.956685, "_runtime": 28.262557983398438, "_step": 4}', '{"Test Accuracy": 0.0, "Epoch": 1, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5}']}, 'output.log': {'offset': 0, 'content': ['2024-03-13T12:05:46.878008 当前脚本的参数如下：\n', "2024-03-13T12:05:46.878008 Namespace(batch_size=64, img_size=64, input_size=64, epochs=20, learning_rate=1e-06, weather='rainy', task='P', model='resnet18', mixNum=0)\n", '2024-03-13T12:05:46.878008 当前训练<雨天-车位分类器>\n', '2024-03-13T12:05:46.878008 EPOCH:0\t\tLOSS:7.051665306091309\n', '2024-03-13T12:05:46.878008 Epoch:0\t\tACCURACY:0.00%\n', '2024-03-13T12:05:46.878008 EPOCH:1\t\tLOSS:6.884834289550781\n', '2024-03-13T12:05:46.878008 Epoch:1\t\tACCURACY:0.00%\n']}}, 'dropped': 0}}
2024-03-13 20:07:57,774 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:07:58,704 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:00,737 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:02,769 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:02,815 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:04,810 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:06,856 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:07,858 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:08,908 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:10,946 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:12,901 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:12,980 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:15,028 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:17,070 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:17,929 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:19,162 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:21,192 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:22,949 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:23,223 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:25,250 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:27,288 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:27,983 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:29,329 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:31,349 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:33,003 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:33,393 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:35,423 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:37,463 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:38,016 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:39,505 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:41,538 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:43,056 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:43,589 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:45,610 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:47,642 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:48,103 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:49,750 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:50,845 WARNING FileStreamThread:28112 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001B802F7ECE0>>, timeout=180), args: ('https://api.wandb.ai/files/princeporch/uncategorized/rubt40t7/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"loss": 6.884834289550781, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5, "Test loss": 0.10974992227554321, "Epoch": 1, "Test Accuracy": 0.0}']}, 'wandb-history.jsonl': {'offset': 1, 'content': ['{"Test loss": 0.11310945415496826, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 1}', '{"Test Accuracy": 0.0, "Epoch": 0, "_timestamp": 1710331536.078492, "_runtime": 21.38436484336853, "_step": 2}', '{"loss": 6.884834289550781, "_timestamp": 1710331540.8136535, "_runtime": 26.119526386260986, "_step": 3}', '{"Test loss": 0.10974992227554321, "Epoch": 1, "_timestamp": 1710331542.956685, "_runtime": 28.262557983398438, "_step": 4}', '{"Test Accuracy": 0.0, "Epoch": 1, "_timestamp": 1710331542.9576855, "_runtime": 28.263558387756348, "_step": 5}']}, 'output.log': {'offset': 0, 'content': ['2024-03-13T12:05:46.878008 当前脚本的参数如下：\n', "2024-03-13T12:05:46.878008 Namespace(batch_size=64, img_size=64, input_size=64, epochs=20, learning_rate=1e-06, weather='rainy', task='P', model='resnet18', mixNum=0)\n", '2024-03-13T12:05:46.878008 当前训练<雨天-车位分类器>\n', '2024-03-13T12:05:46.878008 EPOCH:0\t\tLOSS:7.051665306091309\n', '2024-03-13T12:05:46.878008 Epoch:0\t\tACCURACY:0.00%\n', '2024-03-13T12:05:46.878008 EPOCH:1\t\tLOSS:6.884834289550781\n', '2024-03-13T12:05:46.878008 Epoch:1\t\tACCURACY:0.00%\n']}}, 'dropped': 0}}
2024-03-13 20:08:51,778 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 20:08:53,173 DEBUG   HandlerThread:28112 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 20:08:53,799 ERROR   gpu       :28112 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
